### ISSUE TITLE
Optional vmware provider option

### ISSUE THREAD

**Issue by richierampage** [hashbangcode/vlad#101]
Hi,

VLAD is working well for me but I use vmware as the vm provider not virtualbox. 

My motivation for using vmware is speed but there are some additional networking benefits that I am yet to use. Have no benchmarking figures to share but vmware it is definitely faster for me.

I thought I would share my findings here and suggest that the provider could optionally specified with something like:

<code>vagrant up provider=vmware_fusion</code> or
<code>vagrant up provider=vmware_workstation</code>

### Vmware and vagrant plugin Licensing
Before you can use vmware, you need to buy licenses for both vmware and vagrant vmware provider. Installation of both are straightforward with details of the vagrant license being found https://docs.vagrantup.com/v2/vmware/installation.html

### Config settings changes for vmware fusion
The following code changes work for me using vmware fusion (mac), pc users will need to tweak these for workstation, I think you just need to change  <code>vmware_fusion</code> to <code>vmware_workstation</code> but not sure.

First, specify vmware image so replace current relative path with:

<code># Configure virtual machine options.</code>
<code>config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"</code>

Then change provider config (of course memory and cpus can be changed to suit):

 <code> config.vm.provider "vmware_fusion" do |v|</code>
 <code>  v.gui = false</code>
 <code>    v.vmx["memsize"] = "2048"</code>
 <code>    v.vmx["numvcpus"] = "4"</code>
 <code>  end</code>

### Issues
I have only had some issues with iptables code not being recognised within mysql task so I removed it! This needs resolving properly really. I have not tested all aspects of vlad.

Happy to work on adding provider parameter feature if you think it is worth it?

Rich

**Comment by geerlingguy** [comment]
In case it's helpful, here's the changes (pretty simple, really) I made to the Drupal VM project to get it working with VMware: https://github.com/geerlingguy/drupal-vm/issues/35

**Comment by richierampage** [comment]
Thanks Jeff, some tweaks have now been made to dev branch of VLAD to cater
for this. Just add --provider=vmware_fusion.

On 24 March 2015 at 16:22, Jeff Geerling <notifications@github.com> wrote:

> In case it's helpful, here's the changes (pretty simple, really) I made to
> the Drupal VM project to get it working with VMware:
> geerlingguy/drupal-vm#35
> <https://github.com/geerlingguy/drupal-vm/issues/35>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbangcode/vlad/issues/101#issuecomment-85587947>.
>



-- 
Office:  01732 874054
Mobile: 07734 733541
Skype: richard.moger
Twitter: richardmoger <http://twitter.com/richardmoger>

**Comment by philipnorton42** [comment]
Is everything in place to allow this to work? If so I'll close this issue.

**Comment by richierampage** [comment]
fine by me. thanks


  [image: photo]
*Richard Moger*
Owner, Claritis Limited
 p:+44 (0)1732 874054 | m:+44 (0)7734 733 541 | e:
richard.moger@claritis.co.uk | w:www.claritis.co.uk | a:The Coach House,
West Malling, Kent ME19 6NA
 <http://twitter.com/richardmoger>
<http://us.linkedin.com/in/richard.moger>
    Latest Tweet: <https://twitter.com/richardmoger> Well done to
@eSynergyITrec <https://twitter.com/eSynergyITrec> for sponsoring the
#AWSSummit. <https://twitter.com/AWSSummit.> Too busy deploying new #drupal
<https://twitter.com/drupal> site to #aws <https://twitter.com/aws> to make
it! http://t.co/M49Z7QLB8h
 10:26 Apr-15 <https://twitter.com/richardmoger/statuses/588287268810575872>
Follow
@richardmoger <https://twitter.com/intent/user?screen_name=richardmoger>
<https://twitter.com/?status=@richardmoger&in_reply_to_status_id=588287268810575872>
<https://twitter.com/?status=RT @richardmoger Well done to @eSynergyITrec
for sponsoring the #AWSSummit. Too busy deploying new #drupal site to #aws
to make it! http://t.co/M49Z7QLB8h>
  <https://twitter.com/richardmoger>
 Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by philipnorton42** [comment]
Awesome :) 
Just thought I would check. Thanks!

**Comment by richierampage** [comment]
No, thank you!


  [image: photo]
*Richard Moger*
Owner, Claritis Limited
 p:+44 (0)1732 874054 | m:+44 (0)7734 733 541 | e:
richard.moger@claritis.co.uk | w:www.claritis.co.uk | a:The Coach House,
West Malling, Kent ME19 6NA
 <http://twitter.com/richardmoger>
<http://us.linkedin.com/in/richard.moger>
    Latest Tweet: <https://twitter.com/richardmoger> Well done to
@eSynergyITrec <https://twitter.com/eSynergyITrec> for sponsoring the
#AWSSummit. <https://twitter.com/AWSSummit.> Too busy deploying new #drupal
<https://twitter.com/drupal> site to #aws <https://twitter.com/aws> to make
it! http://t.co/M49Z7QLB8h
 10:26 Apr-15 <https://twitter.com/richardmoger/statuses/588287268810575872>
Follow
@richardmoger <https://twitter.com/intent/user?screen_name=richardmoger>
<https://twitter.com/?status=@richardmoger&in_reply_to_status_id=588287268810575872>
<https://twitter.com/?status=RT @richardmoger Well done to @eSynergyITrec
for sponsoring the #AWSSummit. Too busy deploying new #drupal site to #aws
to make it! http://t.co/M49Z7QLB8h>
  <https://twitter.com/richardmoger>
 Get a signature like this:
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<http://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
