### ISSUE TITLE
SSH identity not passed from host to guest if running Vagrant >= 1.7.0

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#116]
Original issue title:

"ssh-add functionality no longer working after upgrade to Vagrant 1.7.1"

Steps:

1. Upgrade to latest version of Vagrant (1.7.1)
2. ```vagrant up```
3. ```vagrant ssh```
4. ```ssh-add -L```
5. Guest box will report that ```The agent has no identities.```

I've also noticed that Sequel Pro is now asking me for the ```vagrant``` user's password (also ```vagrant```) every time it wants to connect to a db via ssh (despite having access to Vagrant's insecure key).

Looking at Vagrant's [changelog](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md) I'm guessing that this regression is related to a feature added in v1.7.0:

_If the default insecure keypair is used, Vagrant will automatically replace it with a randomly generated keypair on first vagrant up. [GH-2608]_

I'm gonna attempt to roll back to Vagrant 1.6.5 for now.

**Comment by iAugur** [comment]
Vagrant was updated to not use the insecure key and generate a random key
So you can put the following in the Vagrant file and it will act as before:
````
  # since 1.8 Vagrant uses a random generated RSA key!! we don't want this
  config.ssh.insert_key = false
````

**Comment by danbohea** [comment]
Currently testing what happens if you add this line but are running Vagrant < 1.7.0 (I'm still running 1.6.5 due to this very issue!). Will post back with details so that we can get an appropriate fix in for this.

**Comment by danbohea** [comment]
Vagrant 1.6.5 didn't seem to care so that saves us having to check the Vagrant version and possibly add a requirement for Vagrant 1.7+.

Fixed pushed, closing issue. Thanks for your help @iAugur !
