### ISSUE TITLE
Errors installing XHProf

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#117]
XHProf seems to be having some install troubles. I fixed a couple issues on the fly with https://github.com/hashbangcode/vlad/commit/e037edc8765920fd5300a5c19064d917c772192c but now it seems to be struggling with the SQL install script. Error below: 

```
TASK: [xhprof | run SQL install script] ***************************************
failed: [xmaswizardrodeo] => {"changed": true, "cmd": "mysql --user=vlad --password=wibble xhprof < /var/www/xhprof_html/install.sql", "delta": "0:00:00.009957", "end": "2014-12-26 16:30:29.049754", "rc": 1, "start": "2014-12-26 16:30:29.039797", "warnings": []}
stderr: ERROR 1044 (42000): Access denied for user 'vlad'@'localhost' to database 'xhprof'

FATAL: all hosts have already failed -- aborting
```

This install was for a Ubuntu system, running PHP 5.4.

**Comment by danbohea** [comment]
OK, managed to get this working on a a different system with current dev. Looks like one of my systems has some issues of its own (good job I wrote that OS X provisioning playbook!).

Apologies for the noise.

**Comment by kasperg** [comment]
I do not know if this is a separate issue, but I am still seeing issues installing XHProf with 65a25af170f79d864451a448a1bfa4e87e16352d:

```
TASK: [xhprof | copy SQL install script] **************************************
failed: [vlad] => {"checksum": "751a97c968fb300535f016db38407c49adada0e7", "failed": true}
msg: Destination directory /var/www/xhprof_html does not exist
```

I am new to vagrant but if you need any more info or want me to open a new issue let me know.

**Comment by danbohea** [comment]
@kasperg Pretty sure I fixed that in the dev branch.

If you switch to dev now, be aware that you'll need to change any variables set to `"y"` or `"n"` in your settings file to `true` or `false` respectively.

**Comment by kasperg** [comment]
@danbohea: Yeah - that works. Thanks a bunch!

**Comment by danbohea** [comment]
No worries.
