### ISSUE TITLE
custom_provision yml location

### ISSUE THREAD

**Issue by mrconnerton** [hashbangcode/vlad#121]
Where specific am I suppose to put my custom playbook if I have custom_provision: true? The docs say it lives at ../vlad-custom but what is that relative to? It would be nice to know what files are required, and from the repo root where they would live.

**Comment by danbohea** [comment]
"../vlad-custom" is supposed to be relative to the root of Vlad's codebase. For example:

```
demo-project/
├── vlad-custom/
│   └── [your custom role files]
├── vlad/
│   ├── vlad_aux/
│   ├── vlad/
│   ├── ansible.cfg
│   ├── Vagrantfile
│   └── [and so on...]
└── docroot/
    ├── index.php
    └── [and so on...]
```

The above example assumes that you've set `host_synced_folder` to "../docroot" but you could just as easily nest docroot within the first vlad folder (set `host_synced_folder` to "./docroot").

Does that answer your question?

I'll update the docs to make this more clear. I'll also review what files are required and add detail where needed.

Come to DrupalCamp Brighton and I'll show you in person!

http://www.drupalcampbrighton.co.uk

**Comment by mrconnerton** [comment]
That does answer my question perfectly. I will give it a swing shortly. 

I wish I could cross the pond for the camp but that would be a bit much for me :-)

**Comment by danbohea** [comment]
Aaah right, yeah that my be too big an ask :)

Hold your horses, new docs inbound...

**Comment by danbohea** [comment]
Relevant docs now updated in dev branch: https://github.com/hashbangcode/vlad/blob/dev/vlad/docs/usage/custom_roles.md

**Comment by danbohea** [comment]
Gonna close this now. Feel free to re-open if you still can't get it to behave.
