### ISSUE TITLE
Default host test fails - www is assumed

### ISSUE THREAD

**Issue by kevinquillen** [hashbangcode/vlad#122]
This test fails when provisioning:

```
name: test | default host is setup
  command: curl -I http://www.{{ webserver_hostname }} --resolve 'www.{{ webserver_hostname }}:127.0.0.1'
  register: curl_result
  failed_when: "'HTTP' not in curl_result.stdout"
  changed_when: False
  when: apache_install is defined and apache_install == "y"
  tags: test
```

If you customize the webserver_hostname and webserver_hostname_local variable, you may not use www. I don't. I typically use 'local.sitename.com'.

Either way, wouldn't it be better if the test were:

```
name: test | default host is setup
  command: curl -I http://{{ webserver_hostname_alias }} --resolve '{{ webserver_hostname_alias }}:127.0.0.1'
  register: curl_result
  failed_when: "'HTTP' not in curl_result.stdout"
  changed_when: False
  when: apache_install is defined and apache_install == "y"
  tags: test
```

It would seem that the test would then pass using the alias no matter if the variable was changed or not. Same for the SSL test.

**Comment by philipnorton42** [comment]
Hi Kevin,
Thanks for reporting this. An excellent suggestion.

I've pushed a fix for this to the dev branch.

**Comment by kevinquillen** [comment]
I changed this on my machine, deleted the image and did another vagrant up. The tests passed.

**Comment by kevinquillen** [comment]
There is also some console output at the end of the vagrant up process that says something along the lines of "your new site at http://www.sitename.com is ready" - should also reference the alias variable there as well.

**Comment by danbohea** [comment]
Am just testing a fix for the issue mentioned in the previous comment.

**Comment by danbohea** [comment]
It's a little trickier to handle the last request as that's handled in the Vagrantfile rather than in Ansible. I have it working with a custom setting (like in your setup) but it isn't keen on rendering the default properly and this is likely what most people will see.

For the time being I'm just going to remove the mention of a URL (so that at least it's not wrong) until we have a workable solution.

**Comment by philipnorton42** [comment]
I thought I'd put a fix for this in hadn't I? Let me just double check.

**Comment by danbohea** [comment]
Not for the closing feedback.

**Comment by danbohea** [comment]
Just pushed: https://github.com/hashbangcode/vlad/commit/09bcf7a984b28b43d45ac813b37709fca1814074

**Comment by philipnorton42** [comment]
You are right, maybe I did it at home and didn't push the commit... No biggie, thanks for sorting it Dan :)

**Comment by danbohea** [comment]
"Sorting" may be a little undeserved. More like "sweeping under the carpet" :D

**Comment by philipnorton42** [comment]
This bug has been fixed now. Feel free to re-open this issue if you spot any more instances of www being the default :)
