### ISSUE TITLE
site.retry file gets dumped in default Users dir (OSX)

### ISSUE THREAD

**Issue by kevinquillen** [hashbangcode/vlad#127]
If Vagrant fails to provision Vlad, instead of putting the site.retry and related files in the directory Vagrant is building in, it puts it in the default User directory.

For example:

/Hosts/mysite.com/(vlad files)

Vagrant fails, files appear here:

/Users/YourAccount/site.retry

Is there a config to change this or is this a bug?

**Comment by danbohea** [comment]
This is an Ansible default. AFAIK it can't be changed via config.

https://groups.google.com/forum/#!topic/ansible-devel/iOtlm1YbWZ0

Agreed, it can be annoying. I personally use Hazel on OS X to do all the tidying up for me :) I guess a similar script could be cobbled together for free using cron and whatever.

**Comment by kevinquillen** [comment]
I see. I just got a shiny new Macbook so I am trying to keep it garbage
free as long as I can.

**Comment by danbohea** [comment]
Well if that's the case, I can heartily recommend Hazel for all sorts of tasks to help things stay clean and shiny for as long as poss :)

http://www.noodlesoft.com/hazel.php

I'm gonna close this now as it's more to do with default Ansible behaviour as opposed to something we can fix in Vlad.

**Comment by philipnorton42** [comment]
Just to add my 2p. It looks like this feature is incoming -> https://github.com/ansible/ansible/pull/9404

So when it hits we'll add some config rules so that these files get put into a customised directory.

**Comment by danbohea** [comment]
Yay! I guess we should re-open this then so that it can act as a reminder to do that.

**Comment by svenstaro** [comment]
Can't this be closed?

**Comment by danbohea** [comment]
Certainly looks that way. Hurrah!
