### ISSUE TITLE
The LXC provider only works on Linux. Please try to use another provider.

### ISSUE THREAD

**Issue by nlisgo** [hashbangcode/vlad#129]
I am getting this message fairly quickly when I run ```vagrant up```

**Comment by danbohea** [comment]
How exciting!

Nathan, can you share some details about your system? Try the output of the command below plus your host OS etc. Cheers.

```
echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
```

**Comment by philipnorton42** [comment]
Strange that you are having trouble with the system Nathan. I've not used the LXC provider at all so Vlad hasn't really been tested with it. I'd be interested to know how your system is configured, Dan's command should print out all sorts of information about vagrant that will come in handy.

**Comment by nlisgo** [comment]
Sorry for taking so long:

```
$ echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
VirtualBox 4.3.12r93733
Vagrant 1.7.2
ansible 1.6.10
vagrant-aws (0.6.0)
vagrant-cachier (1.2.0)
vagrant-librarian-chef (0.2.1)
vagrant-lxc (1.1.0)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)
vagrant-vbguest (0.10.0)
```

**Comment by nlisgo** [comment]
For not I have uninstalled that plugin. I'm not sure if I am going to need it elsewhere! Guess I'll find out :)

**Comment by nlisgo** [comment]
Seems to have setup fine now. Although I got a couple of FAIL messages on the mailcatcher task. I will open a separate issue.

**Comment by philipnorton42** [comment]
Well, uninstalling the lxc module seems to have fixed things. I'm going to put this down as a plugin issue, rather than a Vlad bug. :)
