### ISSUE TITLE
Amend custom role path & role name

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#141]
This has been nagging me ever since we made the path to vlad_aux configurable. It'll break current setups that use custom roles but I still think we should do it, especially as we're looking to tag 1.0 soon...

The "problem": the custom role name is currently `vlad-custom` and the directory Vlad expects it to exist in is currently named `vlad-custom`. Both use hyphens, not underscores. This goes against Ansible naming conventions (which seems to prefer underscores) and also looks pretty sloppy when you organise your project to look something like this:

```
project/
├── vlad/
├── vlad_aux/
├── vlad-custom/
├── settings/
└── docroot/
```
GHASTLY!!! :D

Call me a pedant, tar me with the OCD brush and call the men in white coats but I think it needs to change to `vlad_custom` and I reckon we should do it before 1.0.

Do I need help?

**Comment by danbohea** [comment]
I should also state for the record that this is likely all my fault.

**Comment by danbohea** [comment]
While we're at it we should probably address the outer settings filenames too (sorry):

- vlad-settings.yml > vlad_settings.yml
- vlad-custom-settings.yml > vlad_custom_settings.yml

Even more breaking changes but we might as well get them all in at once before v1.0 - dev already contains 2 breaking changes as it stands: http://vlad-docs.readthedocs.org/en/latest/project/changelog

**Comment by philipnorton42** [comment]
This makes sense, and seems reasonable :)
+1

**Comment by danbohea** [comment]
Cool, I'll try to get this in today and update docs accordingly.

**Comment by danbohea** [comment]
This is now done. I've also updated the docs accordingly as well as my own custom role for anyone else that might be using that.
