### ISSUE TITLE
VMware OS options

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#144]
Looking through the current Vagrantfile I've just noticed that we're not checking `vlad_os` if using VMware as a provider. It seems that VMware will just use `hashicorp/precise64` as the base box, irrespective of what `vlad_os` has been set to.

**Comment by philipnorton42** [comment]
I'd like to get this corrected before we push live with 1.1.

**Comment by philipnorton42** [comment]
Done. I've no way of testing this, but I think everything is in place and the virtual box provider works correctly.
