### ISSUE TITLE
sequel pro connection issues

### ISSUE THREAD

**Issue by sgrichards** [hashbangcode/vlad#145]
Discussed with @danbohea at Drupalcamp London and agreed that there was an issue with connecting to a vlad box from Sequel Pro (there may be issues with other programs of course) apparently due to changes with vagrant's insecure ssh key.

Made some dirty hacks to a vagrant box and got it working by changing the bind address to that of the box and allowing remote connections on that IP in mysql.

No idea if the above is the way to go but happy to create a pull request if that sounds like a plan?

p.s. good meeting you Saturday @philipnorton42

**Comment by philipnorton42** [comment]
Hi Steve,

Those changes sound good to me. I'm happy with either a pull request or even just popping the settings you've created into this issue and we'll make sure they are applied to the box.

Good meeting you too!

**Comment by danbohea** [comment]
This is now fixed in Dev. Note that the connection settings have now slightly changed as a result (see docs).
