### ISSUE TITLE
Drush make provisioning

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#147]
Allow drush make files to be run (perhaps automatically) from within the Vlad box by creating a 'vlad_aux/make' directory.

Perhaps add a sample “test.make” drush make file to 'vlad_aux/make' directory.

**Comment by danbohea** [comment]
This has now been committed to dev. I opted not to add an example make file given that it would need to reside in vlad_aux which Vlad can create on the fly.

I've added 3 new vars, all fairly self explanatory. Here's the code from defaults/main.yml:

```
# Vlad expects this file to be placed in a subdirectory called "make" within your vlad_aux directory.
# E.g. "vlad_example_d7.make"
# Drush make will not be run if no file is specified.

drush_make_file: ""

# Options to pass to drush make command.
# E.g. "--prepare-install"
# See http://www.drushcommands.com/drush-6x/make/make for possible options.

drush_make_options: ""

# Run drush make every time the VM is provisioned.
# Setting to false will only run drush make if a make file has been specified and docroot is empty (checks for modules directory).

drush_make_force: false

```

I'll update the docs later today.

**Comment by danbohea** [comment]
For convenient and simple testing of this new feature, here is the code from the super basic make file that I used while developing this:

```
core = 7.x

api = 2

projects[drupal][version] = "7.x"

; Use "contrib" as common subdirectory for contrib modules
defaults[projects][subdir] = "contrib"

projects[module_filter][version] = 2.x

```

**Comment by danbohea** [comment]
Docs updated. Will post to Vlad Notices too. Closing.
