### ISSUE TITLE
Different Drush versions

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#148]
Allow Drush versions to be installed much like PHP versions so you either get drush 6 or drush 7.

Although Drush 7 is compatible with Drupal 6 there are a number of issues (http://x-team.com/2015/02/install-drush-drupal-8/) so this should work as follows:

- Drush 6 will be installed as a default.
- Option will allow either Drush 6 or Drush 7 to be installed.
- Vlad will error if this value doesn't match either.

When Drush 7 is stable (or Drupal 8 is released) then Drush 7 will become the default.

Should we also leave in the ability to install the 'drush-master' alias?

**Comment by wizonesolutions** [comment]
+1 because I keep forgetting to use `drush7` for D8.

**Comment by weitzman** [comment]
FYI for Composer managed sites, the best practice is going to be to put Drush into your composer.json and accept that each project gets its own drush.

**Comment by danbohea** [comment]
This is now present in the "galaxy" branch - soon to be in dev with any luck.
