### ISSUE TITLE
Less default software installed

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#149]
In order to prevent the system from taking ages to boot the first time around we need to turn off some options that install software as a default. We should be left with a LAMP stack.

**Comment by philipnorton42** [comment]
Pushed a commit for this so now the default software installed is:

- Adminer
- Apache
- MySQL
- PHP

Varnish is no longer installed as a default.

See commit here: https://github.com/hashbangcode/vlad/commit/63e5b5fbda41eb8258044894939bf84442e0e58a

Leaving open until we (I really) update the docs.

**Comment by danbohea** [comment]
Excellent. Phil, in case you didn't know, if you reference the issue number in the commit message (e.g. "#149") GitHub will automatically add a reference to the commit here on the issue page.

**Comment by philipnorton42** [comment]
I did know, it's just that I was being as thick as a whale omelette and forgot to add the issue number in when I wrote the commit...

I thought referencing the commit the other way around was good enough though :)

**Comment by danbohea** [comment]
Haha :)

**Comment by danbohea** [comment]
This is probably a good example of something that should be reinforced via our fancy new [notice board](https://vladnotices.wordpress.com/) (`<cough>wordpress.com</cough>`): some users will only be setting the bare minimum of vars in their settings file knowing that the defaults are such & such. Now that the defaults are changing, those settings files may now misbehave a little.

What should the workflow for these notices be given that we have both a master & dev branch?

I suggest we add a notice when the change is in dev, we can always then link back to it and anything else via a new notice when a new master tag release comes along.

Also, would it be worth adding a new label to GitHub to indicate that an issue should have an accompanying notice? I'm gonna go ahead and do this, if you disagree then feel free to undo :)

**Comment by danbohea** [comment]
Woop! Notice added to board: https://vladnotices.wordpress.com/2015/03/03/changes-to-which-software-is-installed-by-default/

**Comment by danbohea** [comment]
Docs updated (Variables page). Closing.
