### ISSUE TITLE
Add hosts.ini location to ansible config file

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#151]
Add the hosts.ini location to the ansible.cnf file so that it doesn't need to be specified every time we run a playbook. This has two benefits:

- We can simplify the VagranFile slightly.
- Running Ansible playbooks against the Vlad box means a simpler syntax.

This also means removing config from the VagrantFile and also the documentation.

**Comment by danbohea** [comment]
Done & docs updated.
