### ISSUE TITLE
Allow for better automated testing support

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#153]
Automated testing support currently isn't available as Vlad will ask for sudo passwords. We could create a variable that would prevent the --ask-sudo-pass flag from being set on triggered commands. This would mean that Vlad could be made to run without user interaction.

Sudoers settings need to be correctly in place before this can work though so documentation is needed around this variable.

**Comment by philipnorton42** [comment]
I've moved this to Version 1.1 as we need to get this in place before we can rely on versions

**Comment by philipnorton42** [comment]
I've added the 'suppress_passwords' variable and the needed clauses in the Vagrantfile. I've tested this as working in both situations.

**Comment by danbohea** [comment]
Cool - I've even been considering suppressing passwords somehow in local development just for pure convenience as well as the possibility of opening Vlad up to better integration with other Vagrant tools that seem to freak when it comes to password prompts (PHPstorm's Vagrant tool for one).

**Comment by philipnorton42** [comment]
Today I reverted the 'supress_passwords' variable, but also removed any reference to getting ansible to ask for the sudo password. This is now accomplished by using vagrant plugins to manage local settings. Having the correct sudoers configuration in place will prevent any passwords being asked for.
