### ISSUE TITLE
Create a sample custom role

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#154]
With custom roles being available in Vlad we need to create a sample custom role so that people have a starting point to create their own roles.

**Comment by danbohea** [comment]
Did we agree that this would live in a new GitHub repo?

**Comment by philipnorton42** [comment]
Yes. I think it would be nice to have it sat under the hashbangcode umbrella, along with Vlad and the docs. I think we agreed that I would setup a repo and I would give you access, which I'll get onto now :)

**Comment by philipnorton42** [comment]
It not lives at https://github.com/hashbangcode/vlad_custom_role
Happy to change the name if you want.

**Comment by danbohea** [comment]
Right you are - thanks for reminding me.

Name wise, people will have to either specify a directory name when cloning or remember to rename the directory after cloning as Vlad expects the custom role to be called "vlad_custom". I'd say that for simplicity's sake, it should live at https://github.com/hashbangcode/vlad_custom - we could still stick a great big h1 at the top of the README that reads Vlad Custom Role though if that helps. Thoughts?

**Comment by philipnorton42** [comment]
Having chatting with @IrIna22 we think that it should be https://github.com/hashbangcode/vlad-role

Reasons:
1) It will only ever contain a custom role, not a custom setup of Vlad.
2) Shortening the name is a good idea, so dropping the word custom is fine, this is more or less implied.
3) Hyphens are in use already (e.g. vlad-docs).

But yes, lets H1 the README :+1:

**Comment by danbohea** [comment]
That doesn't really address the point I made in my last comment, or do you not think it's an issue? I personally don't really mind, but that's because I won't be using it :) The people that will be using it may wonder why it isn't made simpler via that small name tweak.

**Comment by philipnorton42** [comment]
No, I saw where you were coming from. Simpler is better. Let's leave it like that for now and run with it.

**Comment by danbohea** [comment]
OK, NP :)
