### ISSUE TITLE
Add support for provisioning with a custom base box

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#156]
This could massively speed up the time required to build a VM especially for teams of devs. The workflow would look something like this:

1. A Vlad instance is configured in the normal way and a VM is built (nothing new here).
2. The new VM is exported as .box file (a Vagrant style image file of the whole VM).
3. Vlad's settings are tweaked to instruct Vlad to build from a custom base box (the .box file we just exported).
4. Any subsequent attempts to provision using those settings will now use the .box file as a starting point (as opposed to a vanilla OS install) and Vlad's Ansible provisioning steps will then be run to ensure that the VM is configured the way that Vlad's settings suggest it should be.

Teams of devs each with access to a central, local server could store .box files there and the "slow" provisioning would have to be done only once by whoever provisioned the VM first. This could also double as a quicker way to rebuild a VM that was previously archived (destroyed but settings preserved) providing that enough disk space is available to store the box files (a fairly minimal Vlad install will weigh in at approx. 600MB).

**Comment by danbohea** [comment]
@philipnorton42 I managed to get a prototype of this working yesterday - I thought I emailed you but I have no record so I'm guessing my email got wonkafied or some other poor bugger received it instead :D

Anyways, we said we'd try this in a new branch - would you mind setting one up and giving me sufficient access? Once setup I'll share what I've done, how you might use it and you can give it a whirl for yourself. It's REALLY fast :)

Also, what milestone should this go under? Do we just aim for 1.1 given that I've already broken the back of it?

**Comment by danbohea** [comment]
It's just occurred to me that this could potentially speed up testing Vlad development a fair bit too. More traditional test scenarios will still be required but some tests could certainly be against a partially provisioned box.

**Comment by danbohea** [comment]
Have created the new branch myself with my new found powers ;)

https://github.com/hashbangcode/vlad/tree/custom-base-box

I'll write up the proper workflow for how to use/test it when I get a chance...

**Comment by danbohea** [comment]
OK, the workflow for testing / demonstrating the features added to the "custom-base-box" branch is as follows:

1. Provision a VM as per normal.
2. Run `vagrant package` (this will halt the VM and create a file named "package.box" in the current directory)
3. Add that new box file to Vagrant's local list of available boxes by running `vagrant box add name_of_box /path/to/package.box` - you create the a name for the box in this step.
4. OPTIONAL: Confirm what boxes are now available to vagrant by now running `vagrant box list` - you should see the box you just added in the list.
6. Run `vagrant up` followed by `vagrant destroy` to destroy the current VM (this is to ensure that we'll be provisioning from scratch later).
7. Add a new var to your settings file: `custom_base_box_name: "name_of_box"`
8. Now run `vagrant up` to boot & provision your VM using the custom box as a starting point and with Ansible still running after to verify the configuration.

Note that this will currently only work with VirtualBox - I'll look at adding VMware support once we're happy with how this is working just with VirtualBox.

**Comment by philipnorton42** [comment]
I still think this idea has legs, so I'm keen to re-roll your changes into version 1.2.

**Comment by danbohea** [comment]
Cool. I'll look at updating the branch after 1.1 lands.

**Comment by danbohea** [comment]
I've just re-rolled the relevant changes for this functionality against the `custom-play` branch. The variable that stores the name of the custom box changed as a result so here's an updated version of the demo steps from above...

----

1. Provision a VM as per normal.
2. Run `vagrant package` (this will halt the VM and create a file named "package.box" in the current directory)
3. Add that new box file to Vagrant's local list of available boxes by running `vagrant box add name_of_box /path/to/package.box` - you create the 'name' for the box in this step.
4. Run `vagrant up` followed by `vagrant destroy` to destroy the current VM (this is to ensure that we'll be provisioning from scratch later and is only really for demo/test purposes).
5. Add a new var to your settings file: `vlad_custom_base_box_name: "name_of_box"`
6. Now run `vagrant up` to boot & provision your VM using the custom box as a starting point and with Ansible still running after to verify the configuration.

*OPTIONAL*: At any step you can confirm what boxes are currently available to Vagrant by running `vagrant box list`.

Note that this will currently only work with VirtualBox - I'll look at adding VMware support once we're happy with how this is working just with VirtualBox.

**Comment by philipnorton42** [comment]
Top work Dan! :+1: I'll give this a go and report back on any issues (although there will likely be none!)

**Comment by danbohea** [comment]
It's really fast and makes the world of difference on my ghetto broadband. My current strategy is to create base boxes of default Vlad setups. E.g:

- vlad_1.1.3
- vlad_1.1.4_dev

I don't deviate from Ubuntu 14 etc much these days so this will make spinning up new project VMs super quick providing I stay on top Vlad's releases.

I can imagine this feature being really handy for teams who will effectively all be provisioning the same box bar any specific local config; in this scenario they may as well all be starting from the same pre-provisioned image.

Keep me posted :)

**Comment by philipnorton42** [comment]
I gave this a shot today @danbohea and it works a treat. It even works when you re-provision the box with different details, like a different apache address.

**Comment by philipnorton42** [comment]
So, I'm going to suggest that we migrate this into Vlad. The functionality it brings doesn't interfere with what's already there and would provide clear benefits to those people who want to use it.

**Comment by danbohea** [comment]
That's great news :)

Given that this work is now rerolled against the `custom-play` branch, I guess next steps involve finalising whatever's needed to merge that branch into dev?

**Comment by philipnorton42** [comment]
I thought everything was self contained in the custom-play branch wasn't it? What sort of things did you have in mind for next steps? I'm thinking I should merge it into dev and then we finalise any loose ends from there on?

**Comment by danbohea** [comment]
Almost, not quite.

- The `custom-play` branch just contains changes necessary for change custom roles to be custom plays (breaking change). There's a matching branch in the docs repo that updates the docs accordingly.
- The `custom-base-box` branch is now based on the `custom-play` branch with the additional changes required to add custom base box support.

In short, if you merge/rebase the `custom-base-box` branch, you *should* be effectively merging both branches.

Comprende?

**Comment by philipnorton42** [comment]
Yes, I see. Let's do it!

**Comment by danbohea** [comment]
Cool. Are you waiting for me to merge this or would you prefer to?

**Comment by philipnorton42** [comment]
No, I was just wondering if we could do it. I'll get on with it now :)

**Comment by philipnorton42** [comment]
Right, all done.
There were a couple of merge conflicts, but nothing too messy :)
I have also updated the documentation with some of the descriptions you have included above.
Awesome work Dan :+1:

**Comment by danbohea** [comment]
Yay!
