### ISSUE TITLE
Add a "hosting_cli" role

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#157]
I currently have an option to install AberdeenCloud's CLI as part of my custom role but I wonder if we'd be better off having a new "hosting_cli" role for this kind of stuff? I'm sure many people would find it useful if Vlad came with optional out of the box support for the most common hosting platform CLIs:

- AberdeenCloud
- Platform SH
- Pantheon

Does Acquia Cloud have an equivalent tool?

**Comment by philipnorton42** [comment]
Agreed on adding this. But lets leave it until after v1.1 :)

**Comment by danbohea** [comment]
:+1:

**Comment by danbohea** [comment]
This won't be making an appearance as originally specced (one role within Vlad). Instead these will be separate roles on Ansible Galaxy. See the current "galaxy" branch for progress (already includes support for Aberdeen CLI & Pantheon CLI).
