### ISSUE TITLE
settings file should not mix project and environment configuration

### ISSUE THREAD

**Issue by zxaos** [hashbangcode/vlad#161]
When editing configuring the settings file, there are a number of variables that control what could be considered project-level settings, such as the hostname, which components to install, the PHP settings, etc. It would be reasonable to expect that everyone working on a project would use the same values for these settings.

However further down in the file, there are settings that are decidedly individual - like ```hosts_file_location```. If you have different developers on a project using different operating systems, this kind of configuration either forces developers to carry around local changes to the settings file or not check the settings file into source control.

To me, it would be more useful if these environment-level settings were broken out into a separate ```local_settings.yml``` or similar file instead, with a default empty fallback. This would allow groups in homogenous environments to still have everything placed in ```settings.yml``` while allowing heterogenous environment groups to easy isolate per-developer settings.

**Comment by danbohea** [comment]
Interesting point - thanks for raising it. As a freelancer I don't bump into these kinds of problems an awful lot as I'm often the only person using Vlad in a team.

Technically, this is fairly straight forward to achieve but I'd like to see how this issue pans out before adding anything to the road map just yet. In the mean time, would you mind listing the exact variables that you'd rather see in a separate `local_settings.yml` file - just to paint an even clearer picture for me and anyone else that joins the thread. Cheers!

**Comment by zxaos** [comment]
Sure! I'm poking at this on my local copy currently, but in case that doesn't go anywhere the variables that stand out to me as being reasonable for this change are listed below. If you're hoping to support windows at some point, then ```synced_folder_type``` is probably especially important.

* ```hosts_file_location```
* ```hosts_file_update```
* ```git_user_name```
* ```git_user_email```
* ```synced_folder_type```
* ```use_host_id```

and I could see a case for these ones in some situations, but am not sure if it would create problems:
* ```boxipaddress```
* ```host_synced_folder```

**Comment by danbohea** [comment]
Thanks that's really helpful. I think you're on to something here :)

**Comment by danbohea** [comment]
This has now been merged into Dev and the docs updated (there may be a delay before the docs appear to have updated).
