### ISSUE TITLE
adding a project page on drupal.org?

### ISSUE THREAD

**Issue by mvancestratfor** [hashbangcode/vlad#174]
There's [little mention of VLAD on drupal.org](https://www.google.com/search?q=site:drupal.org+vlad#q=site:drupal.org+vlad+vagrant). I first started using Vagrant through a [project on Drupal.org called "Vagrant"](https://www.drupal.org/project/vagrant) (which is no longer maintained). I'm sure there are people who could benefit from VLAD (and potentially **contribute**) who don't necessarily think or know to look on GitHub.

Any thoughts on adding a project page on Drupal.org that could be as simple as a quick blurb with a link to the VLAD page on GitHub?

**Comment by danbohea** [comment]
The many guises of @mvance :)
