### ISSUE TITLE
Adding a project page on drupal.org?

### ISSUE THREAD

**Issue by mvance** [hashbangcode/vlad#175]
There's [little mention of VLAD on drupal.org](https://www.google.com/search?q=site:drupal.org+vlad#q=site:drupal.org+vlad+vagrant). I first started using Vagrant through a [project on Drupal.org called "Vagrant"](https://www.drupal.org/project/vagrant) (which is no longer maintained). I'm sure there are people who could benefit from VLAD (and potentially **contribute**) who don't necessarily think or know to look on GitHub.

Any thoughts on adding a project page on Drupal.org that could be as simple as a quick blurb with a link to the VLAD page on GitHub?

**Comment by danbohea** [comment]
I like the sound of this for the reasons described. However, I personally have no experience in maintaining a project on D.O so can't speak for some of the intricacies that may lie in wait:

1. Issues - can these be disabled per project on D.O? Ideally we'd want all issues to continue to be handled here at GitHub - would we have to settle for stating that D.O issues will go unanswered and point people this way?

2. Releases - is it possible to have a project that has no releases? Again, these would ideally originate from the GitHub repo.

3. Given the above 2 points, would Vlad be granted project status on D.O given that from the outset it would only intend to use its project page as a portal to the GitHub repo? I know that Drush is now run in this way but Drush *started* on D.O and I wonder how significant that point is.

What other Drupally projects are run like this that we can learn from?

If anyone here with D.O project experience can answer any of these questions I'd really like to hear your thoughts :) @philipnorton42 do you have any *"real"* Drupal projects? ;)

**Comment by zxaos** [comment]
1. Yes :-)
2. I believe so
3. If @danbohea doesn't have other projects on D.O. we'd need to start it as a sandbox project anyway and get it approved for publication fully.

I agree with this issue, but the challenge would be fitting it into D.O's project structure. Everything must be classified as one of:
* Drupal core
* Distribution project
* Drupal.org project
* Module project
* Theme project
* Theme Engine project
* Translation project

VLAD would be best as either a distribution or a module, but it isn't that great of a match for either. Having said that, [VDD](https://www.drupal.org/project/vdd) is a similar project and is categorized as a Distribution, so that'd probably be the way to go. Given that VDD obviously *was* approved, don't think approval in point 3 is a big bar to clear.

**Comment by iAugur** [comment]
Phil has several modules on D.O  so would be able to get it created as a full project pretty easily I would have thought.

**Comment by danbohea** [comment]
Thanks folks!

Sounds like we have a fairly clear path here. I suggest that if this were to go ahead, @philipnorton42 should be the primary creator/maintainer as that seems both proper/wise given the info shared above, the lineage of Vlad in general and the despicably low level of responsibility that I've managed to maintain this week (don't ask) ;)

Phil is currently experiencing some undesirable internet connection issues at present so I suggest that this issue should remain parked until he can get round to sharing his input.

IMHO, given @zxaos 's list shared above, it seems that D.O's available classifications are a little restrictive, especially for this project. Drush seems to be classified as a module right? This is 100% wonkafied and likely a point that has been raised before but still, maybe it's time for an extra category? I know, I'm in the wrong issue and on the wrong site :)

**Comment by danbohea** [comment]
Dammit! I asked 2 questions in point 1 above, apologies. @zxaos , can you expand on your answer a little? Are you saying that we *can* disable issues?

**Comment by zxaos** [comment]
@danbohea yes, you can disable issues functionality during project creation.

I agree re: the issue categorization, and it's been brought up [before](https://www.drupal.org/node/301466) but seems to be currently stuck in a [big meta issue](https://www.drupal.org/node/322626) that includes both an "Other" category, moving to semver, and improving support for project not tied to a major version of Drupal.

You're correct that Drush is a module, or rather that it was before it moved to github.

**Comment by danbohea** [comment]
It's not clear to me that [D.O Vagrant](https://www.drupal.org/project/vagrant) is no longer maintained. The project page states "Actively maintained" / "Under active development" and the most recent issue querying its status remains unanswered.

Either way, I'd be perfectly happy with "project/vlad" and you could also argue that starting with a clean slate & no previous project history is less confusing.

**Comment by philipnorton42** [comment]
This is an excellent idea. I have a few projects that are full versions so I can create a new 'full' project.

Having done a very quick check on this yesterday I think a distribution is probably the best way to go. It doesn't fit, but it's better than others.

I'll get started :)

**Comment by philipnorton42** [comment]
That didn't take long!
https://www.drupal.org/project/vlad

I'll flesh it out a little more later (and add a logo and things) but it doesn't really need to be more than a signpost page pointing here :)

**Comment by danbohea** [comment]
Ace :)

The fact that we don't have a traditional D.O style issue queue or docs will make this project a bit light on content and searches on D.O may not turn up Vlad when necessary (which is kind of the goal here). ~~Sooo, let's totally spam our project page with keywords :)~~ We should ensure that the project page contains some relevant keywords to compensate:

- Vagrant
- Ansible
- LAMP
- Virtual machine
- VM
- VirtualBox
- VMware
- Ubuntu
- Centos
- Linux
- [all the installed software - PimpMyLog etc]
- and so on...

**Comment by philipnorton42** [comment]
My thoughts exactly, I'll be fleshing it out during the day :)

**Comment by philipnorton42** [comment]
This is now in place. If anyone thinks we need more ~~spammy~~ keyword rich content then let me know.
