### ISSUE TITLE
Error "stdin: is not a tty"

### ISSUE THREAD

**Issue by mbarcia** [hashbangcode/vlad#179]
I've been ignoring this error message upon vagrant up/provision.
"stdin: is not a tty"
It's a minor thing, since it doesn't cause any real problem, but the red message adds confusion to the log on screen.
See https://github.com/mitchellh/vagrant/issues/1673

**Comment by danbohea** [comment]
I've never noticed this with Vlad. Have I just trained my eyes to never see it anymore (having got so used to seeing it elsewhere)?

**Comment by mbarcia** [comment]
You can see it creeping in #46

**Comment by philipnorton42** [comment]
Is there anything we can do about this, I mean other than the Vagrant config suggested in the above bug report? Ie.

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

This is specifically an Ubuntu bug and as such this needs to only be run when running Ubuntu machines. It should therefore fit into the other config in the Vagrantfile. There are plenty of other projects referencing this issue and responses range from "won't fix" to implementing the above config setting and hoping for the best.

**Comment by mbarcia** [comment]
Well, IMO it would be nice if we are able to provide a workaround (if a fix
not possible) to this.

I've seen more than one alternatives to fix this, and I've already tried 2
other to no avail.

I didn't want to mess with such kind of low-level shell stuff, that may
break other things... but it seems we'd need to try uh?

**Comment by philipnorton42** [comment]
Yeah, better to have it fixed than an error. I'm in meetings all day today, but let me know if you find a solution.

**Comment by mbarcia** [comment]
#181

**Comment by danbohea** [comment]
LMAO. I saw the new feedback that now follows this message today. Amazing :D

**Comment by philipnorton42** [comment]
I'm closing this now as we have a fix in place with no reported problems. Thanks @mbarcia :)
