### ISSUE TITLE
Issues with npm packages that use symlinks

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#18]
I'm creating this issue as a note to self as well as to raise awareness.

Whilst adding Node.js support to Vlad I had a go at installing Grunt via npm. In short, it was a headache. It seems that Vagrant has some issues with Node packages that use symlinks (to do with the folder shared between host and guest boxes) and it throws a bunch of errors on install. I tried installing via Ansible with both shell & npm modules, I also tried installing after `vagrant ssh` - all routes resulted in errors and Grunt not installing.

For the record, this is how you should install grunt apparently:

```
#!shell

npm install -g grunt-cli
```

In Vagrant, this will throw a bunch of errors about access problems. Adding `sudo` seems to get round this but I understand that the use of `sudo` is bad form when installing packages so [we probably shouldn't go there](http://howtonode.org/introduction-to-npm).

[Googling around](https://www.google.co.uk/search?q=vagrant+npm+symlink&oq=vagrant+npm+symlink&aqs=chrome..69i57j69i60.4234j0j4&sourceid=chrome&espv=210&es_sm=91&ie=UTF-8) the issue of npm packages that use symlinks returns several posts advising that I add the `--no-bin-links` flag when using `npm install`. Sadly, this didn't work for me and it seems that this advice is mainly born out of users struggling with Windows as a host box (not our concern as Ansible currently means no Windows support for Vlad).

[Another option](http://blog.liip.ch/archive/2012/07/25/vagrant-and-node-js-quick-tip.html) that I've yet to try involves specifically configuring Vagrant to allow symlinks in the shared folder. I'll give this a whirl at some point and update this issue.

---
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/18
- Originally Reported By: [Dan Bohea](http://bitbucket.org/dbohea)
- Originally Created At: 2014-03-12T10:48:21.733

**Comment by BigEdDev** [comment]
I in the past been using [VDD project](https://github.com/x-team/vdd) with Grunt without this issue. This worked on ubuntu with file share. 
Do you think it's worth looking at the architecture to see if there is anything that is different when it comes to configuring vagrant?

**Comment by danbohea** [comment]
> Do you think it's worth looking at the architecture

Personally, no. I much prefer to run Grunt on the host machine as opposed to the guest for a fair few reasons.
