### ISSUE TITLE
.bashrc not loaded for new session

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#180]
Currently I've only tested this in Ubuntu 14 (guest box) provisioned with latest dev branch of Vlad.

Steps to recreate:

1. Provision VM making sure that the PHP role is to be run (Vlad defaults should be fine).
2. SSH into box when provisioned.
3. Run `alias` and see that no aliases are listed. Also try `drush7` or `drush-master` and notice that the guest box doesn't seem to know what on earth you're on about.
4. Manually ensure that .bashrc is loaded by running: `. .bashrc`
5. Now try running any of the following again and notice that it all seems to be working: `alias` / `drush7` / `drush-master`.

I can only assume that somehow .bashrc is not being loaded when you SSH into the box. No idea why though.

**Comment by danbohea** [comment]
Turns out that by default in Ubuntu .bashrc isn't loaded if .bash_profile or .bash_login exists. So all we'd have to do to create the error above is provision a box with either the ruby or bling roles (both will create .bash_profile). Fix incoming...

**Comment by philipnorton42** [comment]
I thought it might be something like that, good spot (and fix).
