### ISSUE TITLE
mysql provisioning fails (on Windows host)

### ISSUE THREAD

**Issue by mbarcia** [hashbangcode/vlad#188]
Latest dev from yesterday, Windows host.

``` 
==> vlad: TASK: [mysql | set the root password.] ****************************************
==> vlad: failed: [192.168.100.200] => {"failed": true}
==> vlad: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
==> vlad:
==> vlad: FATAL: all hosts have already failed -- aborting
```

I checked my "stable Windows Vlad 0.9" and the mysql tasks differ significantly. I've got this working in my local a few months ago, but those fixes never made it into Vlad.

**Comment by mbarcia** [comment]
When in vagrant ssh, mysql can login.

**Comment by philipnorton42** [comment]
Ok, I've rolled this change in to the latest dev branch.

**Comment by philipnorton42** [comment]
Is this working correctly now?

**Comment by philipnorton42** [comment]
Hey @mbarcia can I get an update on this issue please?

**Comment by mbarcia** [comment]
Hello Philip, I stumbled upon this issue in another project I'm currently working on now. 

I _think_ it is the same problem, and its cause has been [explained here](https://github.com/ansible/ansible/issues/4320). 

I've applied [a fix](https://github.com/debops/ansible-mysql/compare/master...mbarcia:master) but still checking whether the fix is solid. So far, it has fixed it in Ubuntu Trusty.

It's tricky to verify because debconf records the data the first time it is executed. Once you've run it a first time then you are no longer able to replicate the problem. You'd have to run something like
```shell
echo PURGE | debconf-communicate mysql-server
```
to see the problem happen again.

Interesting uh?

**Comment by philipnorton42** [comment]
I think this is largely fixed now. It was either to do with the creation of the password file before it is needed (which would only happen if the provisioning failed during the run), or due to the root user not having the correct privileges to access the server. I am going to close this on the assumption that things are fixed, having not seen any requests from users to say otherwise.
