### ISSUE TITLE
sequel pro connection issues - revisited

### ISSUE THREAD

**Issue by pninny2001** [hashbangcode/vlad#193]
This is related to [this previous issue](https://github.com/hashbangcode/vlad/issues/145) with setting up an SSH connection between Sequel pro on the host box and MySQL inside Vagrant.

I had the same symptom, but the solution in the previous ticket is what caused the problem. With the bin-address set to the boxaddress, my SSH connections are being refused. If it's set 0.0.0.0, I get in no problem.

According to the [MySQL docs](http://dev.mysql.com/doc/refman/5.5/en/server-options.html), 0.0.0.0 will accept connections from any IPv4 address.

I'm going to add a pull request with a local override toggle, so we can toggle between the box address and 0.0.0.0.

**Comment by philipnorton42** [comment]
Since this was addressed in pull request #194 I'm going to close this. Thanks for the input :)
