### ISSUE TITLE
Current latest dev break CentOS

### ISSUE THREAD

**Issue by mbarcia** [hashbangcode/vlad#195]
Several components are missing, or just broken. Working on the fix...

**Comment by philipnorton42** [comment]
I'm going to roll some of your changes into Vlad @mbarcia. I like where you were going with many parts of your pull request so I'll update Vlad with those changes.

**Comment by mbarcia** [comment]
Good! as I'm not finding time to test it. I believe if you merge all but skipping the few commits from #197 everything will actually work. You could also merge the whole #199 and afterwards revert those 3-4 commits from #197. Anyway, you'll find the way :-)

**Comment by philipnorton42** [comment]
Ok, I've updated the mysql issue (#188) and also added a couple of things in your recent pull requests.

**Comment by mbarcia** [comment]
Alright, I've updated from dev and re-checked my dev-centos branch. There are still a few changes needed (for CentOS to work under Windows). Need to test now.

**Comment by philipnorton42** [comment]
Cool. I'm on hand if you want me to check things on my end :)

**Comment by philipnorton42** [comment]
Are we able to close this issue yet? I'm not clear on what was not working in the original description so I'm not sure what to test for.

**Comment by philipnorton42** [comment]
@mbarcia also, it'd be great to get an update on this one as well :)

**Comment by mbarcia** [comment]
I opened this issue without much detail on it, because too many things were broken at the time, and got it working on my branch. But the PR was rejected, so I had to split up the changes and but I never really managed to do that and didn't have time in the end to test everything. You can see I committed more work on May 6th. but I never got to test it.

However, many of the fixes were indeed committed, just not 100%.

The test is just firing up a CentOS machine from Windows host, and verify it completes the provisioning (and halts OK as well).

Honestly I don't think I will have time for this now, please feel free to close it, thank you.
