### ISSUE TITLE
Make use of Ansible conditional imports

### ISSUE THREAD

**Issue by mbarcia** [hashbangcode/vlad#196]
Ansible's [conditional imports](https://docs.ansible.com/playbooks_conditionals.html#conditional-imports) can load vars_files based upon ansible facts (ansible_*). This allows us to set values according to OS family and distribuition/release.

This is issue (actually a feature request) is to track an upcoming PR.

**Comment by philipnorton42** [comment]
I'm going to close this as we reworked the final approach into just the MySQL role. I think we'll probably look at doing similar things for other playbooks in the future, but that will be in other issues :)
