### ISSUE TITLE
Optimized defaults for VirtualBox VM

### ISSUE THREAD

**Issue by mbarcia** [hashbangcode/vlad#200]
I'm raising this issue as I think we should be able to optimize the VM of Virtualbox a bit more. In my PC ie., ICH9 chipset performs better than the default. This would also help contributors by shortening the "vagrant up" time in our tests.

I'm seeing [this issue](https://github.com/mitchellh/vagrant/issues/2864) in Vagrant's queue, also [this other post](http://blog.jdpfu.com/2012/09/14/solution-for-slow-ubuntu-in-virtualbox) may prove helpful.

**Comment by philipnorton42** [comment]
This is great, but I'm going to make one slight alteration and remove the extra settings from the example.settings.yml file. We decided a couple of weeks ago to keep that file to an absolute minimum (e.g., box name and installed software) so we really need to remove these parameters.

Other than that, thanks for reworking the Vagrantfile, it was getting a bit messy :P
