### ISSUE TITLE
Option to install extra packages.

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#205]
I'd like to be able to put in something like

````yaml
extra_packages:
  - tmux
````

and get `tmux` installed.

**Comment by philipnorton42** [comment]
Sounds like a good idea to me :+1:

**Comment by danbohea** [comment]
Adding to 1.2 milestone in the interest of not derailing 1.1's release :)

**Comment by philipnorton42** [comment]
Variable added.
