### ISSUE TITLE
Allow configuring max_input_vars in config file

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#206]
I tried running a lot of tests through the D8 UI and got:

`Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0`

I'll have to manually change this currently, which in theory will be wiped out by any future provisioning.

**Comment by mbarcia** [comment]
Hi, I think you can overcome this by creating a ".user.ini" file in Drupal root. HTH, cheers.

**Comment by philipnorton42** [comment]
Here is some information on that: 
http://php.net/manual/en/configuration.file.per-user.php

But I think this is useful to add as a Vlad config option that will alter the php.ini file, especially for Drupal and the dreaded block save page :)

**Comment by mbarcia** [comment]
Well, wouldn't actually be better if Vlad did not mess with the system's php.ini at all? Food for thought.

**Comment by philipnorton42** [comment]
I didn't know about that .user.ini setting in PHP, but that might make sense. It would keep the additional config to a minimum and is platform independent. I'll do some more investigation in the run up to version 1.2.

**Comment by mbarcia** [comment]
Yeah, it's relatively new feature of PHP. And it is important to keep that in mind, because such a change would transfer the responsibility (of modifying php values) to the user and his/her apps. Created another issue to track it.

**Comment by philipnorton42** [comment]
The max_input_vars variable is now part of vlad. The user.ini php files might need a bit more work, but that is beyond the scope of this ticket.
