### ISSUE TITLE
Support for multiple websites with vhosts

### ISSUE THREAD

**Issue by raffone** [hashbangcode/vlad#210]
I was wondering if it was possibile to have multiple websites with one vlad vagrant box. Currently I'm using r8/vagrant-lamp but I'm constantly having problems with vagrant+chef updates, vlad have everything I need to switch but, because I have 50+ wordpress installations, I'd like to keep the current configuration with one vagrant box for all and have separate vhosts. On vagrant-lamp there is a data-bags folder used by chef where are defined all vhosts with id and url.

**Comment by philipnorton42** [comment]
We have this exact feature slated for version 1.2. The first thing we had to sort out was multiple databases and multiple Apache addresses. The next step is to move into a multi hosting setup. I just realised that we haven't added an issue for that though. So thanks! :)

In case you are wondering, 1.1 should be released in the next few days, 1.2 will be a bit longer, but too long.

**Comment by raffone** [comment]
That's great, thanks! But are you sure is that complex to implement (at least for starting with this feature)? On vagrant-lamp there is a simple loop that go through the data-bags' files, and add a new vhost with the extracted ids and urls using a template. No need to have separated databases.

**Comment by mbarcia** [comment]
I think Raffaele's guess is good. There's a setting where you can tell Vlad
about all the virtual servers. You just have to put them all under the
docroot. Sorry I'm being brief I'm not at home. V1.1 will do.

**Comment by philipnorton42** [comment]
I'm going to close this ticket in favour of a new 'meta-ticket'. This ticket proposes a new Apache setup structure which should resolve this issue.
See it here : https://github.com/hashbangcode/vlad/issues/284
