### ISSUE TITLE
Add link to docs site (or a home page) next to short description

### ISSUE THREAD

**Issue by geerlingguy** [hashbangcode/vlad#211]
I keep trying to show people the awesome vlad logo on the docs home page (http://vlad-docs.readthedocs.org/en/latest/), but I forget that the link to the docs site is buried down in the readme file... could you put that link up next to the text `Vlad - Vagrant LAMP Ansible Drupal` on the project home page on GitHub?

**Comment by philipnorton42** [comment]
Done! I've also added some other links to sub-projects and documentation pages. If that isn't clear enough then feel free to reopen this issue :)

**Comment by danbohea** [comment]
> I keep trying to show people the awesome vlad logo
I love this. Any issue that refers to the Vlad logo as "awesome" should be instantly acted upon with full focus & enthusiasm :)
