### ISSUE TITLE
Access vlad instance from another virtualbox VM

### ISSUE THREAD

**Issue by Benjen** [hashbangcode/vlad#217]
I have a VLAD instance running on my ubuntu host system.  As a web developer I want to be able to test my website with Internet Explorer.  Ideally I want to be able to start up a Windows7 vbox guest and then access the VLAD instance from there.

I am not sure how this can be done.

**Comment by danbohea** [comment]
The easiest way to do IE testing IMHO is to use [Vagrant Share](http://docs.vagrantup.com/v2/share/).

**Comment by philipnorton42** [comment]
Yes. Vagrant Share support is baked into Vlad and is probably the easiest way to do this.

The only other way I can think of is to add the hosts rules to the hosts file on the Windows machine.

**Comment by philipnorton42** [comment]
I'm going to close this issue now as it's been a while. More information on vagrant share in Vlad can be found in the Vlad docs -> http://vlad-docs.readthedocs.org/en/latest/usage/vagrant_share/index.html?highlight=share
