### ISSUE TITLE
Cannot create database, user or privilleges through adminer.

### ISSUE THREAD

**Issue by winchendonsprings** [hashbangcode/vlad#218]
After default install trying to modify databases or user fails.

>Access denied for user 'vlad'@'localhost' to database 'test' 23:45:59 SQL command"
 
etc.
>Access denied for user 'vlad'@'localhost' to database 'vladdb' 00:07:21 SQL command

>GRANT GRANT OPTION ON `vladdb`.* TO 'vlad'@'localhost'; -- 0.000 s

VirtualBox 4.3.26r98988
Vagrant 1.7.2
ansible 1.9.1
  configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)
vagrant-vbguest (0.10.0)

**Comment by winchendonsprings** [comment]
I was able to fix this by login into the mysql cli as root and adding the grant option to vlad . After that I could create a db, a user and add privileges. 

Anyway to achieve this by default on provision?

**Comment by philipnorton42** [comment]
Hi @winchendonsprings , thanks for reporting this. It looks like you are using the right versions of things.
What was the configuration option for MySQL you used here?

**Comment by winchendonsprings** [comment]
I tried it completely default and also then destroy and provision with setting dbuser,dbpass, and dbname. Same result.

**Comment by philipnorton42** [comment]
I've added that in now. New version of Vlad with some other minor fixes inbound.

**Comment by winchendonsprings** [comment]
on dev branch. Vlad version reads 1.1.2

Still cannot create database or user
