### ISSUE TITLE
Drush hangs at _drush_recursive_copy() on fresh install

### ISSUE THREAD

**Issue by gitressa** [hashbangcode/vlad#220]
If I try to download Drupal with drush dl on vanilla vlad it hangs at "Calling _drush_recursive_copy".

My setup, using Ubuntu Gnome 14.04:
<pre>echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
VirtualBox 4.3.10_Ubuntur93012
Vagrant 1.7.2
ansible 1.9.1
  configured module search path = None
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)</pre>

I set up a basic vlad instance with these commands:
<pre>git clone https://github.com/hashbangcode/vlad.git
cd vlad/vlad/
cp example.settings.yml settings.yml
VAGRANT_LOG=debug vagrant up
vagrant ssh</pre>

And then try to download Drupal:
<pre>drush dl --debug --destination=/var/www/site/./docroot --drupal-project-rename=drush_example.dev</pre>

After a few seconds the process just hangs after the "Calling _drush_recursive_copy" bit:
<pre>  ...
  drupal-7.37/includes/file.mimetypes.inc
  drupal-7.37/includes/locale.inc
  drupal-7.37/CHANGELOG.txt
Calling chdir(/var/www/site/docroot) [4.4 sec, 7.79 MB]                                      [debug]
Calling is_readable(/tmp/drush_tmp_1431113236_554d0e147c4f7/drupal-7.37) [4.4 sec, 7.91      [debug]
MB]
Calling is_writable(/tmp/drush_tmp_1431113236_554d0e147c4f7) [4.4 sec, 7.91 MB]              [debug]
Calling rename(/tmp/drush_tmp_1431113236_554d0e147c4f7/drupal-7.37,                          [debug]
/tmp/drush_tmp_1431113236_554d0e147c4f7/drush_example.dev) [4.4 sec, 7.91 MB]
Verifying signature for svn version control engine. [4.4 sec, 7.81 MB]                       [debug]
Executing: svn info /var/www/site/docroot
  sh: 1: svn: not found
Verifying signature for bzr version control engine. [4.41 sec, 7.54 MB]                      [debug]
Executing: bzr root /var/www/site/docroot
  sh: 1: bzr: not found
Calling _drush_recursive_copy(/tmp/drush_tmp_1431113236_554d0e147c4f7/drush_example.dev,     [debug]
/var/www/site/docroot/drush_example.dev) [4.41 sec, 7.54 MB]</pre>

I see this is in the log, perhaps it is helpful?

<pre>May  9 16:30:30 vlad kernel: [   90.780075] nfs: server 192.168.100.1 not responding, still trying
May  9 16:32:59 vlad kernel: [  240.300091] INFO: task php:2166 blocked for more than 120 seconds.
May  9 16:32:59 vlad kernel: [  240.300477]       Tainted: G           OX 3.13.0-52-generic #85-Ubuntu
May  9 16:32:59 vlad kernel: [  240.300860] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  9 16:32:59 vlad kernel: [  240.301310] php             D ffff88003fd13180     0  2166   2045 0x00000000
May  9 16:32:59 vlad kernel: [  240.301314]  ffff88003c5adcd8 0000000000000086 ffff88003c150000 ffff88003c5adfd8
May  9 16:32:59 vlad kernel: [  240.301317]  0000000000013180 0000000000013180 ffff88003c150000 ffff88003fd13a18
May  9 16:32:59 vlad kernel: [  240.301320]  ffff88003ffc7ae8 0000000000000002 ffffffff8114ef90 ffff88003c5add50
May  9 16:32:59 vlad kernel: [  240.301323] Call Trace:
May  9 16:32:59 vlad kernel: [  240.301332]  [<ffffffff8114ef90>] ? wait_on_page_read+0x60/0x60
May  9 16:32:59 vlad kernel: [  240.301338]  [<ffffffff81726d2d>] io_schedule+0x9d/0x140
May  9 16:32:59 vlad kernel: [  240.301343]  [<ffffffff8114ef9e>] sleep_on_page+0xe/0x20
May  9 16:32:59 vlad kernel: [  240.301347]  [<ffffffff817271b2>] __wait_on_bit+0x62/0x90
May  9 16:32:59 vlad kernel: [  240.301351]  [<ffffffff8114ed5f>] wait_on_page_bit+0x7f/0x90
May  9 16:32:59 vlad kernel: [  240.301356]  [<ffffffff810ab180>] ? autoremove_wake_function+0x40/0x40
May  9 16:32:59 vlad kernel: [  240.301361]  [<ffffffff8115c4d1>] ? pagevec_lookup_tag+0x21/0x30
May  9 16:32:59 vlad kernel: [  240.301366]  [<ffffffff8114ee69>] filemap_fdatawait_range+0xf9/0x190
May  9 16:32:59 vlad kernel: [  240.301372]  [<ffffffff8115b4ae>] ? do_writepages+0x1e/0x40
May  9 16:32:59 vlad kernel: [  240.301376]  [<ffffffff811505f9>] ? __filemap_fdatawrite_range+0x59/0x60
May  9 16:32:59 vlad kernel: [  240.301381]  [<ffffffff8115070f>] filemap_write_and_wait_range+0x3f/0x70
May  9 16:32:59 vlad kernel: [  240.301390]  [<ffffffffa013b83e>] nfs_file_fsync+0x7e/0x100 [nfs]
May  9 16:32:59 vlad kernel: [  240.301395]  [<ffffffff811eddd6>] vfs_fsync+0x26/0x40
May  9 16:32:59 vlad kernel: [  240.301402]  [<ffffffffa013baca>] nfs_file_flush+0x7a/0xb0 [nfs]
May  9 16:32:59 vlad kernel: [  240.301407]  [<ffffffff811bb51f>] filp_close+0x2f/0x70
May  9 16:32:59 vlad kernel: [  240.301411]  [<ffffffff811dbcbb>] __close_fd+0x7b/0xa0
May  9 16:32:59 vlad kernel: [  240.301415]  [<ffffffff811bb583>] SyS_close+0x23/0x50
May  9 16:32:59 vlad kernel: [  240.301419]  [<ffffffff817330fd>] system_call_fastpath+0x1a/0x1f</pre>

**Comment by danbohea** [comment]
Possibly (likely) related to #216.

**Comment by philipnorton42** [comment]
Agreed. This is the same issue as we are seeing on #216, so I'm going to close this issue as a duplicate. We are aware of the issue with Drush and NFS and are looking into it.
