### ISSUE TITLE
npm install fails in guest due to nfs

### ISSUE THREAD

**Issue by winchendonsprings** [hashbangcode/vlad#222]
Any 'npm install' command hangs forever without finishing if I use nfs. I can get 'npm install' commands to work if the shared folder is rsync though. But that is one way and not what I need.

**Comment by danbohea** [comment]
Very likely related to #216 which I happen to be looking at again right now.

I'm guessing that you're running npm on the guest but installing packages to the host to be seeing this right?

**Comment by danbohea** [comment]
Can you provide details about how `npm install` fails? What error do you get?

**Comment by winchendonsprings** [comment]
Yes, you're right that I'm running `npm install` in the guest, which is a shared folder between the guest and host. 

Since rsync only syncs from host to guest I cannot use it because node/npm live on the guest and not on the host.

npm does not fail with error, but hangs forever or turns into a zombie process if I Ctrl-c it.

**Comment by danbohea** [comment]
Do you not see any of the symptoms described in #223?

**Comment by danbohea** [comment]
@winchendonsprings Can you confirm which version of Vlad you're using?

Also if you don't mind, could you update to the latest version of Vlad dev branch, reprovision a fresh VM and try `npm install` again? Fixes for #216 were committed last night and may have an effect here (I can't recreate what you're experiencing for some reason due to #223).

**Comment by winchendonsprings** [comment]
I have added `nfs_udp: false` to config.vm.synced_folder after type: "nfs" which seems to have fixed the problem. I had to run `npm update` four times in a row and individually `npm install` packages but I was able to complete with no errors.

I'll start a new machine from the dev branch tomorrow and report back again.

**Comment by danbohea** [comment]
Sounds promising - keep us posted.

**Comment by philipnorton42** [comment]
With the new version release with this change in place could we just double check this is working now? The issue seems to be related to nfs rather than node...

**Comment by winchendonsprings** [comment]
Yes, nfs_udp: false to config.vm.synced_folder after type: "nfs" in the new version has fixed it.
