### ISSUE TITLE
Continuos 403 Forbidden

### ISSUE THREAD

**Issue by killua99** [hashbangcode/vlad#227]
All the time, randomly I get that message for my website. I double check everything file permission apache permission, mysql state. Everything right.

How I can help to send any log or setting file?

**Comment by philipnorton42** [comment]
Are the forbidden messages from Drupal or from Apache? I'm assuming it's an Apache message but it's worth checking.
Maybe uploading the settings and log files to [pastebin](http://pastebin.com/) (or similar) might be a good idea.
Thanks for not putting it all into this issue :)

**Comment by philipnorton42** [comment]
Closing as I don't have enough information to go on to propose a fix.
