### ISSUE TITLE
Add to documentation, installing ansible to ubuntu 14.04

### ISSUE THREAD

**Issue by antonyanimator** [hashbangcode/vlad#229]
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

**Comment by philipnorton42** [comment]
Done.

**Comment by danbohea** [comment]
I think we should just link to the relevant page of the Ansible docs for installation instructions. Responsibility for updating instructions is then handed off to Ansible themselves.

http://docs.ansible.com/intro_installation.html
