### ISSUE TITLE
Cannot create new databse or user with 'vlad' user in MySQL.

### ISSUE THREAD

**Issue by winchendonsprings** [hashbangcode/vlad#230]
This is a follow up to https://github.com/hashbangcode/vlad/issues/218

The workaround is to login into mysql cli as root user and add privileges and grant oprion to user 'vlad'

**Comment by philipnorton42** [comment]
Sorry about that, I thought I had it solved. I'll get back on it :)

**Comment by philipnorton42** [comment]
Now in version 1.1.3.
