### ISSUE TITLE
Image styles not generating

### ISSUE THREAD

**Issue by xaviemirmon** [hashbangcode/vlad#238]
Hi Guys,

I can't seem to get the image styles to re-generate on my site.   I have tried all the normal tricks with the file perms (chmod-ing /sites/mysite.dev/files to 777) to no avail.  Have you had any issues with this?

**Comment by danbohea** [comment]
Have you tried deleting the styles subdirectory as part of your chmod-ing? Also, are you including your temp directory as part of your chmod-ing (can't remember if that makes a difference in this instance)?

I'm guessing this isn't a Vlad thing...

**Comment by danbohea** [comment]
@xaviemirmon Did you ever get to the bottom of this?

I was just [reading](https://github.com/blinkreaction/drude/blob/master/.docker/docs/drupal-settings.md#file-permissions-fix) about Drupal file permissions issue with Vagrant & NFS share and thought of this issue.

**Comment by xaviemirmon** [comment]
@danbohea I haven't managed to figure it out nor have I had the time.   I will have a look at that link and let you know if I have any luck.  Cheers!

**Comment by danbohea** [comment]
I don't think this is Vlad issue. Happy to be proven wrong though. Closing - please re-open if you get more info.
