### ISSUE TITLE
PHP versions?

### ISSUE THREAD

**Issue by kevinquillen** [hashbangcode/vlad#242]
Is it possible to install the latest versions of PHP 5.6 and possibly 7?

**Comment by danbohea** [comment]
- 5.6: yes but not on Ubuntu 12
- 5.7: not currently

http://vlad-docs.readthedocs.org/en/latest/applications/php/

**Comment by philipnorton42** [comment]
We should already have the latest version of PHP 5.6. Correct me if I'm wrong here :)

PHP 7 is currently in development and therefore would need to be compiled. Having done this recently (http://www.hashbangcode.com/blog/compiling-and-installing-php7-ubuntu) and seen first hand how long this step takes I would suggest that we wait until a full release (and therefore available in the apt-get/yum channels) before baking it into Vlad.

We could potentially add a flag for PHP 7 that would mean PHP isn't installed, but you may as well start with an empty box in this case.

**Comment by philipnorton42** [comment]
So I'm going to close this issue for now. When a full release of PHP 7 is announced then we'll re-visit this.
