### ISSUE TITLE
Locale is not correctly configured on host machine Ubuntu Gnome 14.04

### ISSUE THREAD

**Issue by raj45** [hashbangcode/vlad#244]
The solution is to reinstall the language package inside the box:
<pre>sudo apt-get install --reinstall language-pack-en-base</pre>

**Before reinstalling the language package**
<pre>
✝ vladtest ✝ /var/www/site/docroot $ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_DK.UTF-8
LC_TIME=en_DK.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_DK.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_DK.UTF-8
LC_NAME=en_DK.UTF-8
LC_ADDRESS=en_DK.UTF-8
LC_TELEPHONE=en_DK.UTF-8
LC_MEASUREMENT=en_DK.UTF-8
LC_IDENTIFICATION=en_DK.UTF-8
LC_ALL=</pre>

**After**
<pre>✝ vladtest ✝ /var/www/site/docroot $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8</pre>

**Comment by philipnorton42** [comment]
I'm going to close this as I'm not seeing this issue on the latest box downloaded from vagrant cloud.

**Comment by raj45** [comment]
The message <code>locale: Cannot set LC_ALL to default locale</code> happens because LANG and LC_ALL are sent to the remote sshd, so that the remote ssh session has the same locale as the local user's session. (From [Ansible permits ssh to send local LANG and LC_ALL env vars (file misencoding, filename corruption)#10698](https://github.com/ansible/ansible/issues/10698)).

The solution for me (on a Debian 8) was to comment out <code>SendEnv LANG LC_*</code> in the <code>/etc/ssh/ssh_config</code> file - I no longer get the locale warnings.

There is a better Ansible-based solution in the "Ansible permits ssh to..." post, which is a bit more complicated, but apparently should fix this issue, without user's having to edit their /etc/ssh/ssh_config file.
