### ISSUE TITLE
Improve bash

### ISSUE THREAD

**Issue by raj45** [hashbangcode/vlad#246]
I always add this to ~.bashrc on Ubuntu machines - is it worth considering adding to Vlad?

<pre># history search with arrow up-down, fx type "cd" and press arrow up
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Previous/next word shortcut with Ctrl + Left Ctrl + Right
bind '"\eOC": forward-word'
bind '"\eOD": backward-word'

# better dir colours
LS_COLORS='di=0;32' ; export LS_COLORS

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=50000
HISTFILESIZE=500000</pre>

**Comment by philipnorton42** [comment]
These changes look fine so I don't see why they shouldn't be included. Do you know if they work on Centos or are these very much 'Ubuntu only'? If they don't work on Centos then I'll need to create a os specific task :)

**Comment by iAugur** [comment]
Customising bash from the default drab offering is a great idea - but my guess is this will start a wildfire discussion of 'how I like to set up my environment' which will be hard to suit everyone. How about having a local configurable template or file that people can customize as they see fit. It could have some sensible defaults in a master file and include a configurable block for the customisations?

**Comment by danbohea** [comment]
I was thinking the same thing about the potential debate around subjective user preferences. I'm not sure that a template within Vlad is the best way to solve it though.

Given that this is a *fairly* advanced thing to be tweaking, would it be fair to say that further customisation of this kind (including undoing any defaults set by Vlad) should be done via a custom playbook (currently "custom role", change incoming - *sssshhhhhh top secret*).

**Comment by philipnorton42** [comment]
I'm inclined to agree with Dan on this one. Rather than include a larger number of tasks and templates the best approach is indeed to include a custom playbook that contains those bash customisation tasks. To facilitate this we could write a custom playbook that could be included if needed, but that's different issue :)
