### ISSUE TITLE
Concurrently running more than one instance of vlad on same host

### ISSUE THREAD

**Issue by Benjen** [hashbangcode/vlad#249]
I am using vlad for website development on my Macbook.  From what I gather it is not possible to run two guests at the same time if those guest VMs are built with vlad.  It seems issues occur with the host systems /etc/hosts file if you try to start up a second guest VM using vlad.

Since I often jump between projects it would be cool if I could have more than one vlad instance up and running at the same time.  Is this possible?

**Comment by danbohea** [comment]
This is possible, I do it all the time. The key is to ensure that you use a unique IP address for each VM in your Vlad settings file.

**Comment by philipnorton42** [comment]
This is perfectly possible, as Dan said you need to ensure that each box has a unique IP address, but you also need to ensure that the box names are unique. The most Vlad machines I have running at once is about 5, but I normally have 2-3 running at any one time.

**Comment by danbohea** [comment]
Doh! Yes, box names too.

See `boxname` http://vlad-docs.readthedocs.org/en/latest/usage/variables

**Comment by raj45** [comment]
I can't see <code>vm_cpus</code> nor <code>vm_memory</code> in vlad/settings.yml. Have they been added recently?

From my settings.yml file:
<pre>
...
# Vagrantfile configuration
  boxipaddress: "192.168.100.100"
  boxname: "vladbibdk"
  host_synced_folder: "./docroot"
# or on Windows
#  host_synced_folder: "C:\\docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true
...</pre>

**Comment by danbohea** [comment]
`vm_cpus` and `vm_memory` will both just use default values unless you specify otherwise in your settings file. From the docs:

> `vm_cpus`
> 
> Number of CPU cores to be allocated to the guest VM from the host machine. This can be an integer or can be set to "auto" for Vlad to automatically assign all available cores.
> 
> default value: '2'
> 
> `vm_memory`
> 
> Amount of memory to be allocated to the guest VM from the host machine. This can be an integer (MB) or can be set to "auto" for Vlad to automatically assign 1/4 of host machine's memory.
> 
> default value: '1024'

**Comment by raj45** [comment]
Sure, I understand. Thanks for answering me here anyway :-)
