### ISSUE TITLE
Can't send emails - MX records not resolvable

### ISSUE THREAD

**Issue by twerthmueller** [hashbangcode/vlad#252]
Hi,

I would like to send mails over drupal/sendmail but the connection to outside servers is always refused.
After some debugging I could see, that the VM can't resolve the MX records and uses instead the IP form the A record. 

From mac terminal:
<img width="494" alt="fullscreen_15_07_15_18_51" src="https://cloud.githubusercontent.com/assets/6920143/8704348/afa45edc-2b22-11e5-8a75-512f7a8a46f3.png">

From the vlad vagrant box:
<img width="540" alt="fullscreen_15_07_15_18_54" src="https://cloud.githubusercontent.com/assets/6920143/8704407/14a94748-2b23-11e5-8a5a-8dde3edcdbec.png">
The MX record is missing on the VM.

I'm not sure is this problem related to vlad, but I don't have this problem with other vagrant ubuntu VM's.

I hope someone has a hint to solve this problem.

Best regards,
Thomas

**Comment by philipnorton42** [comment]
Hi @twerthmueller,

Thanks for reporting this, I had the same problem on a brand new test box. I was able to track this down to the natdnshostresolver1 setting in the Vagrant file. Turning this setting off allows the DNS records to be looked up correctly. I think it's a VirtualBox bug, but I'm not certain....

To prove this now works I ran the same test from my test environment.

```
✝ vlad ✝ /var/www/site/docroot $ dig -tMX cyon.ch

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> -tMX cyon.ch
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59381
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3

;; QUESTION SECTION:
;cyon.ch.			IN	MX

;; ANSWER SECTION:
cyon.ch.		14400	IN	MX	0 cyon.ch.

;; AUTHORITY SECTION:
cyon.ch.		86400	IN	NS	ns1.cyon.ch.
cyon.ch.		86400	IN	NS	ns2.cyon.ch.

;; ADDITIONAL SECTION:
cyon.ch.		14400	IN	A	194.126.200.10
ns1.cyon.ch.		14400	IN	A	194.126.200.5
ns2.cyon.ch.		14400	IN	A	82.197.166.234

;; Query time: 29 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Tue Jul 21 13:44:18 UTC 2015
;; MSG SIZE  rcvd: 125
```

That looked ok, so I ran a further test.

```
✝ vlad ✝ /var/www/site/docroot $ host cyon.ch
cyon.ch has address 194.126.200.10
cyon.ch mail is handled by 0 cyon.ch.
```

Everything seems to be correct now.

This has now been pushed into the dev branch and will be released in a few days.
