### ISSUE TITLE
db_import_up settings always ignored

### ISSUE THREAD

**Issue by ctorgalson** [hashbangcode/vlad#255]
I've been experimenting with adding VLAD to my dev workflow--it's kind of awesome.

Anyhow, I have not been able to make `db_import_up` settings have any effect. Strictly in terms of behaviour, providing any value seems to be interpreted as `true` which leads ansible to try to import a file with *the exact name of the database* (i.e. with no file extensions etc). 

So if my directory structure looks like this:

```
$ ls ..
docroot settings  vlad  vlad_aux
```

...my settings file is located at `settings/vlad_settings.yml`, and includes the following lines:

```
aux_synced_folder: ./vlad_aux
boxipaddress: 10.0.0.8
boxname: dbimportup
db_import_up: dbimportup.sql
dbname: dbimportup
host_synced_folder: ./docroot
synced_folder_type: rsync
webserver_hostname: dbimportup.local
webserver_hostname_aliases:
  - www.dbimportup.local
``` 

I see the following errors from Ansible:

```
TASK: [mysql | mysql_import | import database(s) from default source file(s)] *** 
failed: [10.0.0.8] => (item=dbimportup) => {"failed": true, "item": "dbimportup"}
msg: target /var/www/site/vlad_aux/db_io/halt_destroy/dbimportup.sql.gz does not exist on the host
...ignoring

TASK: [mysql | mysql_import | import database(s) from specified source file(s)] *** 
failed: [10.0.0.8] => (item=dbimportup) => {"failed": true, "item": "dbimportup"}
msg: target /var/www/site/vlad_aux/db_io/dbimportup does not exist on the host
...ignoring
```

I've tried various permutations for the value of `db_import_up`, *none* of which have ever a) imported a database, or b) even resulted in a different error message.

---

I have little experience with Ansible, but looking at `playbooks/roles/mysql/tasks/mysql_import.yml`, [it looks to me as though line 30 of the `mysql_import.yml` file is the problem](https://github.com/hashbangcode/vlad/blob/master/vlad/playbooks/roles/mysql/tasks/mysql_import.yml#L30)--I can see what it's meant to do but given that I've been unable to trigger the final option, it looks to me as though that condition can't evaluate as true.

Reasons why I'm wrong quite welcome :)

--

Added:

OS: Ubuntu 15.04

```
$ ansible --version
ansible 1.9.1
```

**Comment by danbohea** [comment]
> it's kind of awesome

Splendid :)

Can you let me know what version/branch of Vlad you're running?

**Comment by ctorgalson** [comment]
Latest `master` branch.

**Comment by zxaos** [comment]
@ctorgalson I think that with that setup the `vlad_aux` folder should actually be at `vlad/vlad_aux`. I'm pretty sure the paths in the settings are all relative to the Vagrantfile

**Comment by danbohea** [comment]
@zxaos Good spot! Paths are indeed relative to the Vagrantfile. This would mean that the `docroot` directory is also in the wrong place compared to your settings.

Either your settings need to be tweaked (extra `.` at the beginning of each path):

```
aux_synced_folder: ../vlad_aux
host_synced_folder: ../docroot
```

or you need to move `docroot/` & `vlad_aux/` so that they're nested within `vlad/`:

```
$ ls
settings  vlad
$ ls vlad/
README.md  Vagrantfile  ansible.cfg  docroot  vlad  vlad_aux
```

Note that Vlad will automatically create both `docroot` & `vlad_aux` based on your settings if it does not find those directories already in place - this may help you debug if you're still having problems (e.g. you could delete your current `vlad_aux`, run provisioning and then see where Vlad creates the directory).

**Comment by ctorgalson** [comment]
@zxaos & danbohea:

I should have mentioned that I'm trying to follow [the "2 repos parallel" project structure](http://vlad-docs.readthedocs.org/en/latest/usage/project_structure/#2-repos-parallel) so that I can source control a project's dev environment (Vlad), and the project itself separately (there had to be *one* critical bit of info I'd leave out...)

In the docs, it shows a structure like the one I'm using where `vlad_aux`, `settings`, and `docroot` are **siblings** of the main `vlad` directory:

```
demo-project/
├── vlad/
│   ├── vlad/
│   ├── ansible.cfg
│   ├── Vagrantfile
│   ├── README.md
│   ├── .gitignore
│   └── .git/
├── vlad_aux/
├── settings/
│   └── vlad_settings.yml
└── docroot/
    ├── .git/
    └── [drupal codebase...]
```

This is the specific model I'm trying to get working.

**Comment by danbohea** [comment]
@ctorgalson If that's the case then you'll definitely want to set the following two variables like so:

```
aux_synced_folder: ../vlad_aux
host_synced_folder: ../docroot
```

**Comment by ctorgalson** [comment]
Apologies for not returning to this sooner. I appreciate the suggestions, but his issue, as far as I can tell, is either 

1. An error in documentation, or
2. A reproducible bug.

Documentation-wise, I believe my setup is correct (referring to the documentation on [`db_import_up`](http://vlad-docs.readthedocs.org/en/latest/usage/variables/#mysql) and [`2 repos parallel`](http://vlad-docs.readthedocs.org/en/latest/usage/project_structure/#2-repos-parallel)).

From these I conclude:

- (as @danbohea points out, above) that the settings file should have `host_synced_folder` set to "../docroot" and `aux_synced_folder` set to "../vlad_aux", and
- database names and dumps should be provided as arrays even if there is only a single item.

I've done both of these things, but I continue to see errors related to `db_import_up`. I'm completely confident that my setup is correct, because everything but `db_import_up` is functional. Moreover, I've discovered one way to make `db_import_up` work (see "What actually works", below), but it seems odd to me.

## Project structure

```
vladtest
  + example.com
     + docroot
  + settings
     + vlad_settings.yml
  + vlad
  + vlad_aux
    + db_io
      + vladtest.sql
```

## `vlad_settings.yml`

```
aux_synced_folder: ../vlad_aux
boxipaddress: 10.0.0.5
boxname: test
db_import_up: ["vladtest.sql"]
dbname: ["vladtest"]
host_synced_folder: ../example.com/docroot
synced_folder_type: rsync
webserver_hostname: vlad.test
webserver_hostname_aliases:
- www.vlad.test
```

## Error messages.

I continue to see this error message--please note that the filename specified in `vlad_settings.yml` is **not** the name that appears in the error message, even though the file exists in the project directory (`./vladtest/vlad_aux/db_io/vladtest.sql`) and gets correctly copied into the vm (`var/www/site/vlad_aux/db_io/vladtest.sql`):

```
TASK: [mysql | mysql_import | import database(s) from specified source file(s)] *** 
failed: [10.0.1.9] => (item=vladtest) => {"failed": true, "item": "vladtest"}
msg: target /var/www/site/vlad_aux/db_io/vladtest does not exist on the host
...ignoring
```

## What actually works

Unless I'm much mistaken, the source of my issue is at [line 24 of `mysql_import.yml`](https://github.com/hashbangcode/vlad/blob/master/vlad_guts/playbooks/roles/mysql/tasks/mysql_import.yml#L24)--it looks to me as though Ansible will try to import a file with no file extension (since it uses the name of the database):

```

- name: mysql_import | import database(s) from specified source file(s)
  mysql_db:
    name: "{{ item }}"
    state: import
    target: /var/www/site/vlad_aux/db_io/{{ item }}
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: dbname
  when: db_import_up != true and db_import_up != false and mysql_tables.stdout == ""
  ignore_errors: yes
```

And in fact, when I replace the db dump `vladtest.sql` with a file named `vladtest`, the database is successfully imported.

I can't tell if this is by design or not, but the docs for `db_import_up` say:

> ["path_to_file","path_to_file"] - import from vlad_aux/db_io/[path_to_file]. Requires an entry for
> each database specified in dbname. Supports .sql, .bz2 and .gz files.

As written, I interpret this to mean that any of `vladtest.sql`, `vladtest.sql.bz2`, or `vladtest.sql.gz` should work. None of them does.

Thoughts?

**Comment by danbohea** [comment]
Thanks for all the info. I've just recreated this so will have a closer look and see about a possible fix.

**Comment by danbohea** [comment]
This should now be fixed in the dev branch.

@ctorgalson If you could confirm that this fixes things at your end then I'll close this issue.

**Comment by ctorgalson** [comment]
Yes it's definitely working now, thanks! Much appreciated.

**Comment by danbohea** [comment]
Lovely. Jubbly.
