### ISSUE TITLE
Change vagrant-cachier scope to box

### ISSUE THREAD

**Issue by zxaos** [hashbangcode/vlad#257]
Until multiple sites in one vlad install are better supported (1.2?) could we change vagrant-cachier to use the `:box` scope rather than the `:machine` scope? It'd increase efficiency for people running one-vlad-per-project.

**Comment by danbohea** [comment]
http://fgrehm.viewdocs.io/vagrant-cachier/usage

Just reading up on this and it seems like a sensible amend. @philipnorton42 ?

**Comment by philipnorton42** [comment]
Yup, seems perfectly fine to me. I'll get that done today :)

**Comment by philipnorton42** [comment]
All done. That will be in the next release of Vlad :)

We just need to be aware that provisioning multiple boxes at once might cause the "SystemError: Failed to lock /var/cache/apt/archives/lock" error to occur. That's an edge case though...
