### ISSUE TITLE
Rename ./vlad directory

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#258]
I think we should rename the `vlad` directory to anything other than "vlad" or anything that sounds remotely like "vlad". To be clear, I'm talking about the one that lives *next* to the `Vagrantfile`.

It's too often (though not always) nested inside another directory named "vlad" and this in itself can make certain common conversations unnecessarily complicated. In fact, every time I have such a conversation I think to myself *"This is nuts - we really should rename that directory."* and then I just totally forget.

I'd like to kick things off with some suggestions - please put your own forward if you think you can improve in any way:

1. wizard_fireball
2. farmhouse
3. c_drive
4. wizard_fireballs

**Comment by philipnorton42** [comment]
You raise a good point Dan. I've ran through Vlad with a few people and the number of times I've had the exact same conversation is crazy. "Not that 'vlad' directory, the one inside the 'vlad' directory."

Lets change! It's a relatively easy fix, doesn't break too much, and should simplify the documentation as well.

- dalv (i.e. vlad backwards, more or less a current trend I have with naming things...)
- coffin
- stake
- internals

**Comment by danbohea** [comment]
I'm liking "internals". Off the back of this I thought of "guts" which benefits from being even shorter and mildly more disgusting :)

**Comment by philipnorton42** [comment]
'guts' could work. I threw 'internals' in there as a more technical thing, but it sort of works doesn't it? Following on from that, what about 'heart', in keeping with the Vlad theme? :P

**Comment by danbohea** [comment]
> I threw 'internals' in there as a more technical thing, but it sort of works doesn't it? 

Yes I wondered if that was intended to be more technically or biologically inclined. I think that anything that hovers in that grey area is highly appropriate given that this is a technical project with a bizarre coincidental horror theme. I'd be happy with "internals" or "guts". "heart" has further fluffy/sparkly connotations that I thought we'd agreed never go anywhere near :)

https://www.google.co.uk/search?q=vampire+heart&espv=2&biw=1570&bih=1083&site=webhp&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIuMzq64XsxgIVC5rbCh3lIQLg

**Comment by philipnorton42** [comment]
Indeed. I think 'guts' has it. Do we also need to prefix it with 'vlad_' to make sure it doesn't ever clash with other projects in case it's in the same directory?

**Comment by danbohea** [comment]
> prefix it with 'vlad_' to make sure it doesn't ever clash with other projects in case it's in the same directory

Seems smart - we might as well while we're at it.

`vlad_guts' FTW!

**Comment by philipnorton42** [comment]
Done. I've tested it with provisioning a box and all seems to be ok.

**Comment by danbohea** [comment]
Yay! More disgusting directory names please :)

**Comment by christopher-hopper** [comment]
Why this link between `vlad` and a vampire? Why not embrace the more obvious and endlessly more amusing Vladamir Putin as the poster boy for `vlad`. There's so much more amusement that could be mined and without offending people from the east of Europe.
![putin-wink](https://cloud.githubusercontent.com/assets/452515/13206584/4b80b25c-d955-11e5-9ab4-2daf0b6fc7a1.jpg)
