### ISSUE TITLE
Rename vlad_guts/settings.yml

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#261]
Once again, in order to simplify things that have mutated over time, I propose we rename another thing...

I reckon vlad_guts/settings.yml should be renamed to vlad_guts/vlad_settings.yml

This will mean that all project settings files will share the same name, regardless of differing possible locations. This is best illustrated by viewing [the current docs page for settings files](http://vlad-docs.readthedocs.org/en/latest/usage/settings_file/).

While we're at it, we may as well rename vlad_guts/example.settings.yml to vlad_guts/example.vlad_settings.yml for consistency.

**Comment by philipnorton42** [comment]
This gets a most enthusiastic :+1: from me.

(I need to look this up every time I run Vlad so I've noticed this myself, great suggestion Dan!)

**Comment by danbohea** [comment]
Nice one, I'll get this done as soon as I get a chance.

**Comment by philipnorton42** [comment]
Well, I might have a go if I have some free time. I'll let you know either way :)

**Comment by philipnorton42** [comment]
In fact, if either of us have the time then we should just assign it to ourselves. I'll look out for that when I start :)

**Comment by danbohea** [comment]
OK, cool. Likewise :)

**Comment by philipnorton42** [comment]
I forgot to tag the commit message, but the commit here is:

https://github.com/hashbangcode/vlad/commit/7edc3c9573664ce53bcc6f3cafae7652e5d4a841

**Comment by danbohea** [comment]
I guess we should do his for local_settings.yml too? (change to vlad_local_settings.yml)

**Comment by danbohea** [comment]
Done (galaxy branch).
