### ISSUE TITLE
failing at "Install Ruby" step in VLAD 1.1.4

### ISSUE THREAD

**Issue by mvance** [hashbangcode/vlad#263]
I'm having trouble when I enable the `ruby_install` option in the latest 1.1.4 release of VLAD. The provisioning fails and the Ansible debugging output pointed me to the ruby-build log file, where I found the following towards the bottom:

```
installing capi-docs:         /home/vagrant/.rbenv/versions/2.1.2/share/doc/ruby
The Ruby readline extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libreadline-dev` to fetch missing dependencies.
```

If I get a chance to debug it some more later, I'll update the ticket, but for now I'm going to disable Ruby.

**Comment by frederickjh** [comment]
mvance fix also solved the problem I was having getting Ruby to install.

**Comment by danbohea** [comment]
Sounds like this can be closed.
