### ISSUE TITLE
Accessing guest VM from host network

### ISSUE THREAD

**Issue by Benjen** [hashbangcode/vlad#268]
I love using Vlad for my development work.  However, one area I find could be improved, would be to provide a way to access the VM from computers on the same network as the host. Being able to do this would enable one to test the website using various mobile devices.

Would be good if there was an configuration option to enable one to use bridged networking instead of NAT or, alternatively, set up port forwarding.  The problem I have now is that my host network uses 10.0.0.x but my vlad VM uses 192.168.100.x

**Comment by philipnorton42** [comment]
Have you seen Vagrant share?
http://vlad-docs.readthedocs.org/en/latest/usage/vagrant_share/

If this doesn't really do what you need then we could look at adding more configuration options. The reason that Vlad uses host network is that it's more reliable (in my experience) for accessing the VM and prevents network IP address clashes (which can be ugly).

**Comment by philipnorton42** [comment]
I'm going to close this now on the context that Vagrant Share is a good solution to this issue. This doesn't preclude changing the VM provider network settings, but that's a pretty major change that might not be needed and might even cause more issues than it solves.

**Comment by danbohea** [comment]
Related: #287.
