### ISSUE TITLE
New variable 'apache_document_root'

### ISSUE THREAD

**Issue by twerthmueller** [hashbangcode/vlad#270]
It would be great to have a variable like 'apache_document_root' (default: /var/www/site/docroot), to overwrite the apache document root (and Directory-directive) when necessary. Then we don't need to edit the 'apache_vhost.j2' template.

This way it's possible to set a different path as a relative path to 'host_synced_folder'. Sometimes we need to point to a subdir of '/var/www/site/docroot' as a document root.

Thanks for the great work!

**Comment by twerthmueller** [comment]
Is it possible to get this variable in a next version of vlad?

**Comment by philipnorton42** [comment]
Yes I think so. We've been making some high level architectural changes to Vlad recently, but now is the time to start getting the Apache setup sorted. I've added a milestone for the next minor release :)

**Comment by twerthmueller** [comment]
This would be great! Thanks a lot for your work!!

**Comment by philipnorton42** [comment]
I'm going to close this ticket in favour of a new 'meta-ticket'. This ticket proposes a new Apache setup structure which should resolve this issue.
See it here : https://github.com/hashbangcode/vlad/issues/284
