### ISSUE TITLE
Additional steps needed when installing Redis

### ISSUE THREAD

**Issue by johncook** [hashbangcode/vlad#275]
When setting `redis_install: true` PHP redis module is not installed. The procedure from the http://stackoverflow.com/questions/11424547/php-redis-error has to be followed.

The resolution would be to either:
- install php-redis and update php.ini files when provisioning or
- document the requirement in example.vlad_settings.yml and vlad-docs.

**Comment by philipnorton42** [comment]
Thanks for pointing this out @johncook :+1: 
This has now been added to the dev branch. I will release it as a new version of Vlad soon. In the meantime, if you spot any problems then please let me know!
