### ISSUE TITLE
tmp directory is not automatically created so vagrant up fails

### ISSUE THREAD

**Issue by raj45** [hashbangcode/vlad#288]
Reapperance of #167 - I am also using Ubuntu 14.04. This is the error where it fails:

<pre>TASK: [base | ensure certain vlad_aux subdirectories exist] ******************* 
failed: [192.168.100.100] => (item=tmp) => {"failed": true, "item": "tmp", "parsed": false}
BECOME-SUCCESS-ukryunbrffvmnueruzrjdtginfcmpfdn
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1445002967.23-196068892008677/file", line 2012, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1445002967.23-196068892008677/file", line 279, in main
    os.mkdir(curpath)
OSError: [Errno 2] No such file or directory: '/var/www/site/vlad_aux/tmp'
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/raj45/.ssh/config
debug1: /home/raj45/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.100.100 closed.

failed: [192.168.100.100] => (item=db_io) => {"failed": true, "item": "db_io", "parsed": false}
BECOME-SUCCESS-xwrwddfjvinohhoumxftobnapjqhhgfl
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1445002967.36-266518121813680/file", line 2012, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1445002967.36-266518121813680/file", line 279, in main
    os.mkdir(curpath)
OSError: [Errno 2] No such file or directory: '/var/www/site/vlad_aux/db_io'
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/raj45/.ssh/config
debug1: /home/raj45/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.168.100.100 closed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/raj45/site.retry

192.168.100.100            : ok=4    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.</pre>

**Comment by danbohea** [comment]
Can you confirm what version of Vlad you're running?

**Comment by danbohea** [comment]
The reason I ask is because [up until a few days ago](https://github.com/hashbangcode/vlad/commit/979328058b2ede10c6e60bda1f3cf6174f63b147#diff-755389542508f342178a1079fd198b09) (dev branch) this task was performed with sudo (seemingly inexplicably). Perhaps this was the reason.

**Comment by danbohea** [comment]
@raj45 Please can you try Vlad latest dev and let us know if you're still getting this error?

**Comment by raj45** [comment]
@danbohea Absolutely, but I am not sure how to check out to the dev-version... I usually just <code>git clone https://github.com/hashbangcode/vlad.git</code>.

**Comment by danbohea** [comment]
If that's the case then it's likely that the change I committed today will not fix anything for you.

In case I'm wrong, here's how to grab the latest `dev` version via an existing local cloned repo:

```
git checkout dev
git pull
```

If you ever then want to jump back to `master` (the branch you had checked out by default) just run:

```
git checkout master
```

**Comment by raj45** [comment]
Thanks for the guidance. I tried the latest dev-version, but get the same error...: <code>OSError: [Errno 2] No such file or directory: '/var/www/site/vlad_aux/tmp'</code>.

**Comment by zxaos** [comment]
@raj45 , if you create the tmp directory in the host OS before provisioning, does it work?

**Comment by raj45** [comment]
@zxaos, this bug has disappeared in the master branch, I just made a complete Drupal installation with these commands:

<pre>git clone https://github.com/hashbangcode/vlad.git
cd vlad/
vagrant up --debug
vagrant ssh
drush dl --verbose --drupal-project-rename=example.local
cd example.local
drush site-install --db-url=mysql://vlad:wibble@localhost/vladdb --account-name=admin --account-pass=admin --yes</pre>
