### ISSUE TITLE
How to add another Drupal website?

### ISSUE THREAD

**Issue by drupality** [hashbangcode/vlad#289]
I'm a newbie in Vlad and Vagrant at all.

I've setup Vlad with a single Drupal site, so docroot is in /var/www/site/docroot.

Now I want to add second Drupal site, but I've no idea how to do it properly,
How to set another host path in Vlad config file?

I've read the docs but found nothing in this topic. Maybe I missed something

**Comment by zxaos** [comment]
Hi @drupality . Currently it's not possible, but the feature is planned. You can follow along progress for it in #284 where the syntax for the configuration is being discussed.

**Comment by philipnorton42** [comment]
Yeah, it's not possible at the moment, but feel free to post your thoughts and suggestions on #284 which is where the work is being done :)

**Comment by drupality** [comment]
Thanks for the info people :)

**Comment by danbohea** [comment]
@drupality - Just in case the thought hadn't already crossed your mind: you can have more than one instance of Vlad (effectively one VM per Drupal site). That's currently how we do it. If your second site is a separate project, this may be all you need (and is completely possible right now).
