### ISSUE TITLE
Second vagrant shared folder

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#29]
The notion of a second vagrant shared folder originally floated by Phil in issue #19 and I didn't want to lose sight of it, hence creating this issue. 

Issue 19 deals with "deprovisioning" on `vagrant destroy` and among other things is an opportunity to make a last minute database dump to preserve config that could otherwise be unintentionally zapped. The current system gets the job done but could be improved: the db dump is saved to docroot/ which is likely your Drupal project and therefore likely in version control and therefore likely not where you want a db dump to suddenly appear.

Creating a second shared folder would allow us to improve on this and also do much more. E.g:
1. Save a db dump to a location outside of docroot/ but still available after the VM has been destroyed.
2. Optional auto import of a db dump on `vagrant up`.
3. Optional rsync of the entire Drupal private files directory if present (which could very possibly be located outside of docroot/), preserving the entire backup set (scheduled & manual) if using the backup_migrate module.

To kick off, I propose the following in terms of structure (I've suggested that the new shared folder is called 'aux'):

```
.
├── README.md
├── Vagrantfile
├── ansible.cfg
├── aux/
│   ├── README.md
│   ├── db_io/
│   │   ├── destroy/
│   │   │   └── README.md
│   │   └── up/
│   │       └── README.md
│   └── rsync/
│       └── README.md
├── docroot/ << (not in git)
├── example.settings.yml
├── playbooks/
└── settings.yml << (not in git)
```

Notes:
- Configure vagrant to sync aux/ with another directory named 'aux' within the VM. Exact location to be discussed but I'm leaning towards /var/www/site/aux as it places it right beside docroot - mirroring the setup on the host box.
- **aux/db_io/** would contain db files to be imported on `vagrant up` and exported on `vagrant destroy` (dump files stored in subdirectories named respectively).
- **aux/rsync/** would be used to store any files copied with rsync on `vagrant destroy`.
- **README.md files** added all over the place to aid with basic documentation and to ensure that this otherwise empty directory structure gets included in the Git repo.
- **.gitignore** would need some love in order to keep dynamic stuff out of Vlad's repo when developing & testing (e.g. dump files in aux/db_io etc)

If "aux" means something else that's very important within a Linux based web server then please let me know - I don't want to cause confusion and am open to ideas. [A quick Google search](http://goo.gl/Ed9EiI) suggests that it's probably OK.

Regarding the playbooks that would handle interaction with aux/, let's start by tweaking the current sql dump on destroy mechanism and then tackle the others later once we've had a chance to think it through more and get some of the above folder structure in place.

---
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/29
- Originally Reported By: [Dan Bohea](http://bitbucket.org/dbohea)
- Originally Created At: 2014-04-06T15:37:23.769

**Comment by chriscalip** [comment]
at the file settings.yml what variable handles the Second vagrant shared folder ?

**Comment by danbohea** [comment]
`aux_synced_folder` is what you're after. But that variable was introduced after this original conversation which is so old it started on BitBucket.

Familiarising yourself with the current docs will yield better results than looking to year old issues:

http://vlad-docs.readthedocs.org/en/latest/usage/variables

Also, there is no file called settings.yml anymore, it's now vlad_settings.yml. Again, _[docs](http://vlad-docs.readthedocs.org/en/latest/)_.

Furthermore, tacking support requests on to closed enhancement discussions isn't helpful. Please think before you post.
