### ISSUE TITLE
Commands working very slow

### ISSUE THREAD

**Issue by drupality** [hashbangcode/vlad#291]
First I've encountered that drush is working very slow. I was start thinking that this maybe php/mysql config issue. But when I tried 'git status' the case was the same. ~15sec to see an output...

How can I speed this up?

**Comment by danbohea** [comment]
First time I've ever heard anything like this reported. My first suggestion would be to increase the resource allocation to the guest via Vlad's settings. You could start with (I generally always use this as a default):

```
vm_cpus: "auto"
vm_memory: "auto"
```

That should be an increase from the defaults, there's room to assign even more memory from the host if you feel the need, just specify how much as an integer like so:

```
vm_memory: 2048
```

More info: http://vlad-docs.readthedocs.org/en/latest/usage/variables/#vagrantfile-configuration (see `vm_cpus` and `vm_memory`)

**Comment by philipnorton42** [comment]
@drupality Did any of Dan's suggestions improve things at all? Or are you still seeing slowdowns?

**Comment by philipnorton42** [comment]
Assuming that @danbohea's suggestions are working correctly and this was a resources issue I'm going to close this issue.
