### ISSUE TITLE
Automating basic site tasks (utility to create multiple sites)

### ISSUE THREAD

**Issue by chriscalip** [hashbangcode/vlad#296]
Who wants it? Can we have it?

Lets have a drush script that automates basic site tasks : 
- Configure DNS by editing the /etc/hosts file
- Configure Apache by creating a virtualhost for `example1.drupal.local`
- Create a MySQL database called example1
- Download the most recent Drupal release from drupal.org
- Run the Drupal 7 installer (without a web browser)

Based on the utility tool provided by drupal.org/project/quickstart
Getting started with Quickstart
Automating basic site tasks
https://www.drupal.org/node/819398 

`drush quickstart-create example1.drupal.local`
`drush qc example1.drupal.local --make=drupal7.make`
`drush quickstart-destroy example1.drupal.local`
`drush qd example1.drupal.local`

**Comment by chriscalip** [comment]
By extension this requires host_synced_folder
a.) Host folder as dictated by vlad_settings.yml host_synced_folder
b) Corresponding virtual-machine instance points to maybe /var/www/sites/ instead , or make this configurable instead

**Comment by danbohea** [comment]
I'm not sure I completely understand what it is you're looking to do here. Most if not all of this is already achievable with Vlad already (albeit not all via a Drush script).

**Comment by chriscalip** [comment]
Right the idea is to have a configurable and reproducible ability to create a site in the vm instance.
For example I want to create these sites in the vm instance : 
example1.drupal.local
example2.drupal.local
example3.drupal.local
example4.drupal.local

So, to accomplish these tasks.. should be easy as doing : 
`drush qc --domain=example1.drupal.local`
`drush qc --domain=example2.drupal.local`
`drush qc --domain=example3.drupal.local`
`drush qc --domain=example4.drupal.local`

These does update etc/apache2/sites-available, etc/apache2/sites-enable, creates database schemas (example1,example2,example3,example4), update corresponding site /sites/default/settings.php files.

the problem with vm instance /var/www/drupal7_install.sh and rest of bash scripts.. is these scripts are hard-coded to just docroot :(
