### ISSUE TITLE
Build fails at initial Pantheon check if certain default vars aren't overridden

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#301]
I've been playing with the new Pantheon stuff and just bumped into a bug whereby the build fails with the error below if your settings do not override certain defaults (that's as close as I've come to troubleshooting this tonight - I'm hoping to get a tiny bit closer to knowing wtf is going on here):

```
TASK: [Check Pantheon Import dependencies] ************************************
fatal: [192.168.100.177] => error while evaluating conditional: vlad_pantheon_import_site and (mysql_install == false or pantheon_cli_install == false)
```

If I add the following to my vlad_settings.yml then the build passes the early checks as expected:

```
db_import_up: true
pantheon_cli_install: true

# New Pantheon stuff
vlad_pantheon_import_site: true
vlad_pantheon_import_site_email: vlad@example.com
vlad_pantheon_import_site_password: ihategarlic
vlad_pantheon_import_site_site: somesite
vlad_pantheon_import_site_env: live
vlad_pantheon_import_site_include_files: false
```

Vlad latest latest dev.
VirtualBox 5.0.8r103449
Vagrant 1.7.4
ansible 1.9.4
  configured module search path = None
vagrant-cachier (1.2.0)
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.0)

I should add that I've checked out a few different commits right back to when this code was merged  and the error is consistent (was worried that I'd broken something today).

cc @wizonesolutions

**Comment by wizonesolutions** [comment]
It could be that I missed setting one of the defaults in my role on which
the role relies. Take a peek at the other conditions: do they also check if
defined or not? That might be the issue.

**Comment by danbohea** [comment]
I don't have a load of time to properly debug & fix this right now but I'm also conscious of dev effectively being broken if you're not intending to use the new Pantheon import stuff.

I suggest we move the new Pantheon stuff into a separate branch until it's fixed up. Thoughts?

**Comment by wizonesolutions** [comment]
I have that presentation Saturday, so I can fix it tomorrow.
12. nov. 2015 11:06 skrev "Dan Bohea" <notifications@github.com>:

**Comment by wizonesolutions** [comment]
Reproduced! Troubleshooting!

**Comment by wizonesolutions** [comment]
I think this is fixed now, yeah? It's just that I'm not a maintainer, so it couldn't auto-close this issue.

**Comment by danbohea** [comment]
Sorry! Drowning in real work and Vlad things to test. I will get back to this I promise! :)

**Comment by danbohea** [comment]
Yep, this looks fixed. Thanks for sorting it!
