### ISSUE TITLE
Unify base boxes?

### ISSUE THREAD

**Issue by zxaos** [hashbangcode/vlad#308]
Now that opscode is publishing their "bento" baseboxes on Atlas, it would be possible to update vlad to use the same base box for every provider:

* bento/ubuntu-14.04
* bento/ubuntu-12.04
* bento/centos-6.7

All of these options have virtual box, vmware, and parallels providers.

So the consequences specifically would be:
* Updating CentOS to 6.7 from 6.6.
* Moving away from `parallels/` base boxes for the parallels provider
* Moving away from `hashicorp/precise64` for Ubuntu 12.04
* Moving away from `ubuntu/` base boxes for the VirtualBox provider
* All supported base box configurations will be automatically updated through atlas.

Any thoughts about this?

**Comment by philipnorton42** [comment]
Some really good changes here @zxaos :)
I think changing over to a single provider is a good idea, makes everything more streamlined. The simplification of the Vagranfile is also an awesome change.
We'll need to run some tests, but if everything else is ok with the changes then I think we'll run with it :)

**Comment by zxaos** [comment]
Ok, looks like there's going to need to be at least some fixes.

The drupal_console task fails on centos:

``` TASK: [drupal_console | Download the latest version of Drupal console] ********
changed: [192.168.100.183]

TASK: [drupal_console | Create Drupal console symlink] ************************
failed: [192.168.100.183] => {"failed": true, "path": "/usr/local/bin/drupal", "src": "/home/vagrant/console.phar", "state": "absent"}
msg: src file does not exist, use "force=yes" if you really want to create the link: /home/vagrant/console.phar

FATAL: all hosts have already failed -- aborting```

Weirdly though, when I tried running the download by hand with the same command the task uses, it worked fine. (i.e., I think it's the first command that's reporting "changed" that's actually failing - console.phar is indeed absent).

**Comment by zxaos** [comment]
Closing the original PR for this for a moment since (a) I needed to move it onto a different branch and (b) it's not ready for merge anyway until the centos stuff is fixed. [The commits are still over at my fork for now](https://github.com/zxaos/vlad/tree/308-unify-base-boxes)

**Comment by danbohea** [comment]
I'm liking this concept more and more. Just wasted a fair bit of time debugging what was actually just a difference in base boxes between VirtualBox & VMware - this kind of consolidation would have helped minimise that.

**Comment by danbohea** [comment]
Drupal Console is disabled in `dev` for now: https://github.com/hashbangcode/vlad/commit/8989a05c9802735f99f263ae2df3309ad7e559fc

**Comment by zxaos** [comment]
@danbohea If we're ignoring the Drupal Console for now, I can open a new PR for this code since I believe that was the major blocker.

**Comment by zxaos** [comment]
Hmm. Centos 6.7 provisions fine, but fails if you try to run `vagrant provision` a second time.

**Comment by jmolivas** [comment]
Which version of DC is causing this issue?. We fixed Drupal-VM, issues on latest release and must be working now.

**Comment by danbohea** [comment]
See #314.

**Comment by wizonesolutions** [comment]
+1 on this from me. I just had issues with `parallels/ubuntu-14.04` and Bento worked fine. We will still need to have provider-specific configuration, but the box selection code would be *much* simpler (we can just let people override the base box if they want to use another one).

**Comment by danbohea** [comment]
Sounds like we're all fairly keen to get this in then. Can I suggest we merge this into `dev` and begin testing from there?

@philipnorton42 I'm particularly looking for sign off from you here :)

**Comment by philipnorton42** [comment]
I'm happy with this. The only caveat is that we need to announce this change before it gets released :)

**Comment by danbohea** [comment]
> The only caveat is that we need to announce this change before it gets released :)

Absolutely.

**Comment by zxaos** [comment]
Great! Now we just need to finish #253 :shipit: and 1.17 is totally ready immediately right? :sunglasses:

(Want me to close this or do you need to keep it open for release notes?)

**Comment by wizonesolutions** [comment]
@zxaos So what is the actual way to use old boxes after this change? I tried setting `vlad_custom_base_box_name`, but Vagrant says it can't find my VM anymore after I pull `dev` up to where this was merged. I see in the PR that you recommend just destroying and recreating. Is that basically the way to go?

**Comment by zxaos** [comment]
@wizonesolutions If you're using a custom base box, you should be ok. What you're running into is not this, it's actually #312 . The trick will be that you need to move your `.vagrant` folder. It will previously had been beside the Vagrantfile inside vlad's structure, but now vlad will be looking for that folder in the same place as your settings file, wherever that is.

(The indicator on this one is you should be seeing a message saying "Adjusting Vagrant environment and re-initializing" - that's vlad re-targetting the location of the VM folder).
