### ISSUE TITLE
.gitignore Icon?

### ISSUE THREAD

**Issue by njt1982** [hashbangcode/vlad#318]
This is catching the "icons" folder inside /modules/file/ which means no files have any icons on our sites.

**Comment by philipnorton42** [comment]
Thanks for submitting :) 
I noticed this myself and removed it a while ago. The change is currently in the dev branch but there are one or two things that we need to complete first before we can release a new version. This should be soon (it's just that we are all really busy in the run up to the holidays).

**Comment by njt1982** [comment]
sure - I was just about to make a PR for it... so I don't need to fix anything?

**Comment by philipnorton42** [comment]
Nope, the fix is already there :)

Unless there are improvements you can make?

**Comment by njt1982** [comment]
Unlikely - I was just going to remove the line ;)
