### ISSUE TITLE
Build for Drupal8 does not work

### ISSUE THREAD

**Issue by nickeblewis** [hashbangcode/vlad#322]
I can get Vlad to work with Drupal 7 perfectly well and have been using the project for some time. I have tried installing a new instance for Drupal 8 and have hit problems.

The /var/www/drupal8_install.sh script is trying to pull  one of the old Beta branches that seems not to be available any more and as such the script fails. I tried updating the script to install version 8.0.1 and this clones the repo fine but then fails to install the rest as cleanly as the Drupal 7 script.

**Comment by zxaos** [comment]
Hi @nickeblewis - which version of vlad are you encountering this in?

**Comment by nickeblewis** [comment]
I simply cloned the repository, so the latest is it not? Or is there another way of obtaining Vlad?

**Comment by danbohea** [comment]
This should be fixed in the `dev` branch already.

https://github.com/hashbangcode/vlad/commit/091492c8c7ced5a48d1d5dc23b1ef898fbb1adcf

**Comment by nickeblewis** [comment]
Thanks @danbohea - I shall have a look at that :-)

**Comment by nickeblewis** [comment]
That worked a treat, brilliant, thanks guy for a great VM!

**Comment by danbohea** [comment]
Jolly good. Thanks for confirming it worked.
