### ISSUE TITLE
Ansible 2.0

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#327]
http://www.ansible.com/blog/ansible-2.0-launch

We need to start testing against the new release. We also need to review the new features to see if there is much that Vlad would benefit from.

**Comment by philipnorton42** [comment]
So I guess my question is:
At what point (or version) do we say that people should be using a particular version of Ansible?

Personally, I think we should start supporting Ansible 2.0 fully. It isn't that hard to update and there is good support for backwards compatibility.

**Comment by zxaos** [comment]
I agree! Since vlad is a development I don't think it's unreasonable to ask people to follow ansible stables releases relatively closely.

**Comment by wizonesolutions** [comment]
Ansible is pretty easy to update, even with `pip`. That'd free you from thinking about too many things.

If you want max BC, though, then keep an eye on when Ansible plans to remove its now-deprecated functionality and make sure you remove it by then.

**Comment by danbohea** [comment]
Closing as current Vlad dev branch does work with Ansible 2 now.
