### ISSUE TITLE
New behavior — provisioning on vagrant resume

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#329]
Vlad didn't used to re-provision on `vagrant resume`, but now it is. Is this a change to the `Vagrantfile` that I missed? What is the rationale?

**Comment by danbohea** [comment]
This isn't intentional to my knowledge.

**Comment by philipnorton42** [comment]
It should not provision the box entirely, but it does run the local_up.yml playbook in order to ensure that the installed services are running correctly.

**Comment by wizonesolutions** [comment]
No, it's running the actual provisioning process. The `local_up.yml` one
shows up in black. The one it's running shows up in color.

**Comment by wizonesolutions** [comment]
Just to confirm that I saw this again today when resuming, so it wasn't just one-time.

It updates hosts, "configures cache buckets," runs a shell provisioner (presumably to fix the tty thing), "configures cache buckets," and then runs the Ansible provisioner. Pretty sure Vagrant still only runs provisioning once in principle.

**Comment by zxaos** [comment]
Well, configure cache buckets is vagrant-cachier running.
I'd potentially expect to see it twice, since the Vagrant script re-launches itself now to fix the .vagrant location. But three seems odd.

Can you post a full command output of this issue? Just so we can be sure we're seeing the same things?

**Comment by wizonesolutions** [comment]
When I get around to it. I have to sanitize the VM name, which is always a pain.

**Comment by philipnorton42** [comment]
I have removed the resume trigger from the Vagrantfile. I have to say I don't tend to use the suspend/resume workflow much, opting for the halt/up commands instead so I never noticed this issue.

Thanks for pointing it out @wizonesolutions :)

**Comment by wizonesolutions** [comment]
Yeah, I use suspend/resume a lot. I don't think those were doing much from
Vlad's side, since hostsupdater runs anyway without needing a trigger.
Thanks.

**Comment by wizonesolutions** [comment]
@philipnorton42 This doesn't seem to be fixed. I'm up-to-date from `dev` but still seeing the behavior on two VMs.
