### ISSUE TITLE
Bash prompt no longer set by Vlad

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#338]
I've just noticed on a newly provision Ubuntu 14 box that Vlad's attempt to tweak the bash prompt is no longer working. The bling role is still successfully adding the required line to ~/.bashrc but that then appears to be somehow overridden with a different prompt (it shows the current git branch among other changes).

I can't figure out where the new prompt is being set though - any got any info?

**Comment by christopher-hopper** [comment]
This was happening because the `drush init` command call in drush 8.x adds its own custom prompt code. This issue should be fixed now with the changes from #346

**Comment by danbohea** [comment]
Right you are. Thanks again. Closing :)
