### ISSUE TITLE
Cannot override boxipaddress in local settings

### ISSUE THREAD

**Issue by christopher-hopper** [hashbangcode/vlad#344]
### Problem

When using a different `boxipaddress` in a local settings file `vagrant up` gets stuck when it starts to mount synced folders. 

### Steps to Reproduce

1. Download vlad for a fresh project install (I've tried this using both `master` and `dev` branches).
1. Follow the [Getting Started](http://vlad-docs.readthedocs.org/en/latest/usage/getting_started/) steps.
1. Copy the included `vlad_guts/example.vlad_settings.yml` file to `vlad_guts/vlad_settings.yml`.
1. Open `vlad_guts/vlad_settings.yml` and change the `boxipaddress` to `10.0.0.1`.
1. Copy the `vlad_guts/vlad_settings.yml` file to `vlad_guts/vlad_local_settings.yml`.
1. Open `vlad_guts/vlad_local_settings.yml` and change the `boxipaddress` to `10.0.0.200`.
1. Create a folder named `./docroot` for the Drupal install synced folder. 
1. Execute `vagrant up`

### Expected Result

The vagrant machine will be created and started with the folder named `./docroot` for the Drupal install synced into the correct location.

### Actual Result

The vagrant provisioning gets stuck at the point where folders are synced using nfs. Waiting does not produce any further output and `vagrant up` does not finish. 

If you try to force vagrant to stop, using **[CTRL + C]** the ruby vagrant process is left running in the background and must be killed manually. 

### Versions

I'm experiencing this issue on Linux with the following dependency versions:

- Ubuntu 14.04 LTS
- GNU bash 4.3.11(1)-release (x86_64-pc-linux-gnu)
- Vagrant 1.7.4
- ansible 2.0.0.2

**Comment by danbohea** [comment]
Just tested this with current `dev` and am seeing no issue. I should add that I tested 2 separate scenarios:

Override default value from local settings:
- vlad_settings.yml: not specified (will assume default of 192.168.100.100)
- vlad_local_settings.yml: 192.168.100.199

Override custom value from local settings (similar to OP's scenario):
- vlad_settings.yml: 192.168.100.101
- vlad_local_settings.yml: 192.168.100.199

Mac OS 10.9.5
VirtualBox 5.0.14r105127
Vagrant 1.7.4
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
vagrant-cachier (1.2.1)
vagrant-hostsupdater (1.0.1)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.2)

**Comment by danbohea** [comment]
> 7. Create a folder named ./docroot for the Drupal install synced folder.

@christopher-hopper BTW, you should be able to skip this step as Vlad will create the directory for you if it doesn't already exist.

**Comment by christopher-hopper** [comment]
Okay, I think I've tracked it down and it might be my fault. I'm setting an IP address that is slightly different. 

It only happens if I use an IP like `10.0.0.1`, which I thought would be fine. I use these IPs on other non-vlad boxes that have a vagrant network connection that is internal only. If I use the `192.168.x.x` IP it isn't a problem. 

I think I don't care why this is happening, now that I know it can be fixed by simply using the  `192.168.x.x` IP address range.
