### ISSUE TITLE
vlad slowness in D8 seemingly fixed by uninstall of update module

### ISSUE THREAD

**Issue by gitressa** [hashbangcode/vlad#358]
As the title says, not so much an issue as a tip: My vlad installs with Drupal 8 are usually suuuper slow, sometimes taking 10-15-20 seconds for admin pages to load. After I uninstalled the Update module, the admin pages load much faster.

**Comment by philipnorton42** [comment]
I wonder what is going on there then? I have seen a few instances where lots of disc requests will cause a slow down in page loads, which I think may be caused by the NFS interface. Not sure if that is what's going on here though.

**Comment by gitressa** [comment]
It could be interesting to debug. Do you know how I can see if there are a lot of disc requests?

**Comment by philipnorton42** [comment]
I spotted it when using xhprof to benchmark a site. There were a lot of calls to PHP functions like file_exists() and is_dir(), which in turn caused a slow down. Easy to spot when you look at the call-graph. 

For a more general approach you can use commands like ```sysstat``` to see disc reads per second. Although I'm not sure how useful that is here... :)

**Comment by gitressa** [comment]
Ah yes, xhprof is good at that, I'll give it a whirl if the slowness returns, but for now it's pretty fast :-)
