### ISSUE TITLE
Folders and files disappear after logout when installed with composer

### ISSUE THREAD

**Issue by gitressa** [hashbangcode/vlad#361]
After I logout, many folders and files mysteriously disappear, see the images:

## Before logout (a copy I made)
![composer-missing-files-dirs-1](https://cloud.githubusercontent.com/assets/3491208/16206360/5e4f6f82-3728-11e6-940f-020e609ea3ea.png)

## After logout
![composer-missing-files-dirs-2](https://cloud.githubusercontent.com/assets/3491208/16206355/57333382-3728-11e6-920f-ade9e660ae0f.png)

**Comment by philipnorton42** [comment]
I take it from these screenshots that you are using Ubuntu? I've not seen composer delete files before... I wonder what's going on?

**Comment by gitressa** [comment]
Yes, I am using Ubuntu 14.04. I'll try to recreate it, but hopefully it was freak event.

**Comment by gitressa** [comment]
On another note, does it also takes your machine around 15 minutes for composer to download drupal 8? This is what happens after `drush si standard --db-url='mysql://vlad:wibble@localhost/comp_d8' --account-pass=admin --site-name='Composer D8 V2' -y;`

23.31 - Starts up, downloads a lot of stuff, and then hangs at this step:
<pre>- Installing drupal/core (8.1.3)
Loading from cache</pre>
23.41 - continues
23.45 - finished

**Comment by philipnorton42** [comment]
Are you using the ```vlad_drupal_install``` variable at all?

**Comment by gitressa** [comment]
I don't think I am using `vlad_drupal_install`. Where would I set it?

**Comment by philipnorton42** [comment]
It's set to be false as a default, but you can set it to true in the settings.yml files in order to get Vlad to install Drupal for you when the box provisions. It's set to install Drupal 7 as a default, which looks like what it's done for you.

**Comment by gitressa** [comment]
Sorry! It was very late when I posted the download question... (https://github.com/hashbangcode/vlad/issues/361#issuecomment-227282714)

This is the command (download with composer) I should have posted, not the drush install-command: `composer create-project drupal-composer/drupal-project:8.x-dev comp_d8 --stability dev --no-interaction`.

For this project I would like to use Composer, both in development and production, so unfortunately using `vlad_drupal_install` is not an option.

**Comment by gitressa** [comment]
Hi Phil, Nevermind with the Composer question. I think I will be using drush make in stead to download my Drupal 8 modules - it seems less complicated than composer.
