### ISSUE TITLE
Ansible failed to complete successfully

### ISSUE THREAD

**Issue by laurelstreng** [hashbangcode/vlad#373]
Forgive is this something silly, but I'm not familiar with what is going on with this issue:

I cloned the vlad repository, updated the `boxname` in the vlad_settings.yml file, and went to run the initial vagrant up. I've done this plenty of times before with no issues until now, i'm getting the following error:
```
TASK [php : add ppa Repository] ************************************************
fatal: [192.168.100.100]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}
```

`Ansible failed to complete successfully.`

Any help would be greatly appreciated

**Comment by philipnorton42** [comment]
Hi @laurelstreng ,
Thanks for reporting. This is a problem and work is currently being done on the fix on the dev branch. I think most of the problems have been ironed out, I'm just testing different permutations of system and configuration to make sure that it all works correctly.
Sorry for the delay!

Thanks!
Phil
