### ISSUE TITLE
Idempotency: Tasks that still report as 'changed' on second provision.

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#78]
Off the back of pull request #43 & pull request #44, we should be aiming for maximum idempotency for all tasks.

This issue is here to help collectively list all tasks that still report 'changed' on second provision and track the progress of reducing that list.

---------------------------------------
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/78
- Originally Reported By: [Dan Bohea](http://bitbucket.org/dbohea)
- Originally Created At: 2014-09-04T11:30:42.538

**Comment by danbohea** [comment]
A new one:

```
TASK: [php | enable php mcrypt module] ****************************************
```

**Comment by danbohea** [comment]
Old but gold:

```
TASK: [drupal | drush | install drush via composer] ***************************
```

More verbose output contains a clue:

```
"stderr": "Changed current directory to /home/vagrant/.composer\n./composer.json has been updated\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nNothing to install or update\nGenerating autoload files"
```

**Comment by danbohea** [comment]
So, this issue probably isn't the best place to track this. It'll never be closed, parts/most of it will remain out of date, there's no decent facility for checking off the ones we've solved. I see 2 possible solutions:

1. We report these one per issue and tag them "idempotency".
2. We track this in the docs rather than GitHub issues.

I'm leaning towards (1). Quite a lot. In fact, forget I mentioned (2). Thoughts?

**Comment by philipnorton42** [comment]
Option 1 sounds good to me. Having a single issue makes it difficult to select which one has been fixed etc.

Yeah, I'm going to ignore 2 :see_no_evil:

**Comment by philipnorton42** [comment]
So, actions.

Let's fix the two issues you've found today Dan, and then we'll close this and move into the individual idempotency tasks.

**Comment by danbohea** [comment]
Okey dokey.

**Comment by danbohea** [comment]
The following drush task is now fixed in terms of idempotency thanks to Mariano's new approach:

```
TASK: [drupal | drush | install drush via composer] ***************************
```

That just leaves the following in terms of **this** issue:

```
TASK: [php | enable php mcrypt module] ****************************************
```

**Comment by danbohea** [comment]
The following is now fixed in dev:

```
TASK: [php | enable php mcrypt module] ****************************************
```
Closing this now as agreed. All future issues regarding idempotency should be raised as separate, individual issues labelled "idempotency".
