### ISSUE TITLE
Mail doesn't seem to be properly configured

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#87]
Upon a newly setup vlad, I see ``Unable to send e-mail. Contact the site administrator if the problem persists.``

Here's my ``settings.yml``
https://gist.github.com/amitaibu/01756d78ce53cf524e51

Apart of sendmail_install -- is there anything else I should try?

---------------------------------------
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/87
- Originally Reported By: [amitaibu](http://bitbucket.org/amitaibu)
- Originally Created At: 2014-09-21T19:48:15.687

**Comment by philipnorton42** [comment]
This fix is now my main focus in getting version 1.0 sorted out. Hopefully I'll have something working by the end of the week.

**Comment by philipnorton42** [comment]
Just pushed a fix for this issue so now at the very least PHP is sending emails into mailcatcher. We had altered the place that the catchmail program exists and hadn't let PHP know about that. All sorted now.

What about setting up the correct mailman for the box though, is it worth it for a local deal platform? I don't know much about mail servers so I'm keen to know! :)

**Comment by philipnorton42** [comment]
I'm going to close this now as version 1.0 has been released. If we need to revisit the mail settings then I don't mind opening things again, but I think the current setup works.

**Comment by danbohea** [comment]
:dancers:  1.0!!! :dancers:
